Backport tests/openpgp-certs fixes.

diff --git a/tests/openpgp-certs/testselfsigs b/tests/openpgp-certs/testselfsigs
--- a/tests/openpgp-certs/testselfsigs
+++ b/tests/openpgp-certs/testselfsigs
@@ -1,7 +1,30 @@
-#!/bin/bash
+#!/bin/sh
+
+# Copyright (C) 2010 Free Software Foundation, Inc.
+#
+# Author: Nikos Mavrogiannopoulos
+#
+# This file is part of GNUTLS.
+#
+# GNUTLS is free software; you can redistribute it and/or modify it
+# under the terms of the GNU General Public License as published by the
+# Free Software Foundation; either version 3 of the License, or (at
+# your option) any later version.
+#
+# GNUTLS is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with GNUTLS; if not, write to the Free Software Foundation,
+# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
+
+set -e
 
 srcdir="${srcdir:-.}"
-CERTTOOL="${certtool:-../../src/certtool} -q"
+CERTTOOL="${CERTTOOL:-../../src/certtool$EXEEXT}"
+
 unset RETCODE
 
 fail() {
@@ -11,14 +34,20 @@ fail() {
 
 echo "Checking OpenPGP certificate self verification"
 
-( $CERTTOOL --pgp-certificate-info <$srcdir/selfsigs/alice.pub | grep -e "^Self Signature verification: ok" ) >/dev/null ||
-  fail "Self sig Verification should have succeeded!"
+($CERTTOOL --pgp-certificate-info < $srcdir/selfsigs/alice.pub \
+    | grep "^Self Signature verification: ok" > /dev/null) || \
+    fail "Self sig Verification should have succeeded!"
 
-( $CERTTOOL --pgp-certificate-info <$srcdir/selfsigs/alice-mallory-badsig18.pub | grep -e "^Self Signature verification: failed" ) >/dev/null ||
-  fail "Self sig Verification should have failed!"
-( $CERTTOOL --pgp-certificate-info <$srcdir/selfsigs/alice-mallory-irrelevantsig.pub | grep -e "^Self Signature verification: failed" ) >/dev/null ||
-  fail "Self sig Verification should have failed!"
-( $CERTTOOL --pgp-certificate-info <$srcdir/selfsigs/alice-mallory-nosig18.pub | grep -e "^Self Signature verification: failed" ) >/dev/null ||
-  fail "Self sig Verification should have failed!"
+($CERTTOOL --pgp-certificate-info < $srcdir/selfsigs/alice-mallory-badsig18.pub \
+    | grep "^Self Signature verification: failed" > /dev/null) || \
+    fail "Self sig Verification should have failed!"
+
+($CERTTOOL --pgp-certificate-info < $srcdir/selfsigs/alice-mallory-irrelevantsig.pub \
+    | grep "^Self Signature verification: failed" >/dev/null) || \
+    fail "Self sig Verification should have failed!"
+
+($CERTTOOL --pgp-certificate-info < $srcdir/selfsigs/alice-mallory-nosig18.pub \
+    | grep "^Self Signature verification: failed" >/dev/null) || \
+    fail "Self sig Verification should have failed!"
 
 exit ${RETCODE:-0}
