*** empty log message ***

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -373,18 +373,18 @@ AC_SUBST(LIBASN1_LINK)
 
 AC_CONFIG_FILES(lib/gnutls.h.in)
 
-AC_CONFIG_COMMANDS([lib/gnutls.h],[[
- test -f lib/gnutls.h.in || (echo "Could not generate lib/gnutls.h" && exit 1)
- cat lib/gnutls.h.in > lib/gnutls.h
- cat lib/gnutls_ui.h >> lib/gnutls.h
- echo "" >> lib/gnutls.h
- cat lib/gnutls_errors_int.h | grep -v _INT_ >> lib/gnutls.h
- echo "" >> lib/gnutls.h
- echo "#ifdef __cplusplus" >> lib/gnutls.h
- echo "}" >> lib/gnutls.h
- echo "#endif" >> lib/gnutls.h
- echo "#endif /* GNUTLS_H */" >> lib/gnutls.h
- echo "" >> lib/gnutls.h
+AC_CONFIG_COMMANDS([includes/gnutls/gnutls.h],[[
+ test -f lib/gnutls.h.in || (echo "Could not generate includes/gnutls/gnutls.h" && exit 1)
+ cat lib/gnutls.h.in > includes/gnutls/gnutls.h
+ cat lib/gnutls_ui.h >> includes/gnutls/gnutls.h
+ echo "" >> includes/gnutls/gnutls.h
+ cat lib/gnutls_errors_int.h | grep -v _INT_ >> includes/gnutls/gnutls.h
+ echo "" >> includes/gnutls/gnutls.h
+ echo "#ifdef __cplusplus" >> includes/gnutls/gnutls.h
+ echo "}" >> includes/gnutls/gnutls.h
+ echo "#endif" >> includes/gnutls/gnutls.h
+ echo "#endif /* GNUTLS_H */" >> includes/gnutls/gnutls.h
+ echo "" >> includes/gnutls/gnutls.h
  chmod +x lib/libgnutls-config
  chmod +x libextra/libgnutls-extra-config
 ]],[[]])
@@ -393,6 +393,6 @@ AC_CONFIG_FILES([Makefile src/Makefile libextra/Makefile lib/Makefile \
 lib/libgnutls-config libextra/libgnutls-extra-config \
 doc/Makefile src/x509/Makefile src/srp/Makefile src/openpgp/Makefile \
 doc/tex/Makefile doc/tex/cover.tex doc/scripts/Makefile \
-tests/Makefile])
+tests/Makefile includes/Makefile includes/gnutls/Makefile])
 
 AC_OUTPUT
