Only print output if something fails

diff --git a/tests/userid/userid b/tests/userid/userid
--- a/tests/userid/userid
+++ b/tests/userid/userid
@@ -20,9 +20,15 @@
 # along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
-set -e
-
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
 
-exec $CERTTOOL --certificate-info --infile $srcdir/userid.pem
+$CERTTOOL --certificate-info --infile $srcdir/userid.pem >out 2>&1
+RET=$?
+if [ $RET !=  0 ];then
+	echo "Error in userid:"
+	cat out
+	exit 1
+fi
+
+exit 0
