tests: backported testdsa to prevent random failures in test suite

diff --git a/tests/dsa/testdsa b/tests/dsa/testdsa
--- a/tests/dsa/testdsa
+++ b/tests/dsa/testdsa
@@ -23,133 +23,143 @@
 srcdir="${srcdir:-.}"
 SERV="${SERV:-../../src/gnutls-serv} -q"
 CLI="${CLI:-../../src/gnutls-cli}"
-PORT="${PORT:-5558}"
 DEBUG=""
 unset RETCODE
 
-if test "${WINDIR}" != "";then
-  exit 77
+CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+fi
+
+if test "${WINDIR}" != ""; then
+	exit 77
 fi 
 
-. $srcdir/../scripts/common.sh
+. "${srcdir}/../scripts/common.sh"
 
-echo "Checking various DSA key sizes (port $PORT)"
+PORT="${PORT:-$RPORT}"
+
+echo "Checking various DSA key sizes (port ${PORT})"
 
 # DSA 1024 + TLS 1.0
 
 echo "Checking DSA-1024 with TLS 1.0"
 
-launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile $srcdir/cert.dsa.1024.pem --x509keyfile $srcdir/dsa.1024.pem >/dev/null 2>&1 & PID=$!
-wait_server $PID
+launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile "${srcdir}/cert.dsa.1024.pem" --x509keyfile "${srcdir}/dsa.1024.pem" >/dev/null 2>&1 &
+PID=$!
+wait_server "${PID}"
 
 PRIO="--priority NORMAL:+DHE-DSS:+SIGN-DSA-SHA512:+SIGN-DSA-SHA384:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1"
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 1024 key and TLS 1.0!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 1024 key and TLS 1.0!"
 
 echo "Checking server DSA-1024 with client DSA-1024 and TLS 1.0"
 
 #try with client key of 1024 bits (should succeed) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.1024.pem --x509keyfile $srcdir/dsa.1024.pem </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 1024 key and TLS 1.0!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.1024.pem" --x509keyfile "${srcdir}/dsa.1024.pem" </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 1024 key and TLS 1.0!"
 
 echo "Checking server DSA-1024 with client DSA-2048 and TLS 1.0"
 
 #try with client key of 2048 bits (should fail) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.2048.pem --x509keyfile $srcdir/dsa.2048.pem </dev/null >/dev/null 2>&1 && \
-  fail $PID "Succeeded connection to a server with a client DSA 2048 key and TLS 1.0!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.2048.pem" --x509keyfile "${srcdir}/dsa.2048.pem" </dev/null >/dev/null 2>&1 && \
+	fail "${PID}" "Succeeded connection to a server with a client DSA 2048 key and TLS 1.0!"
 
 echo "Checking server DSA-1024 with client DSA-3072 and TLS 1.0"
 
 #try with client key of 3072 bits (should fail) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.3072.pem --x509keyfile $srcdir/dsa.3072.pem </dev/null >/dev/null 2>&1 && \
-  fail $PID "Succeeded connection to a server with a client DSA 3072 key and TLS 1.0!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.3072.pem" --x509keyfile "${srcdir}/dsa.3072.pem" </dev/null >/dev/null 2>&1 && \
+	fail "${PID}" "Succeeded connection to a server with a client DSA 3072 key and TLS 1.0!"
 
-kill $PID
+kill "${PID}"
 wait
 
 # DSA 1024 + TLS 1.2
 
 echo "Checking DSA-1024 with TLS 1.2"
 
-launch_server $$  --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile $srcdir/cert.dsa.1024.pem --x509keyfile $srcdir/dsa.1024.pem >/dev/null 2>&1 & PID=$!
-wait_server $PID
+launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile "${srcdir}/cert.dsa.1024.pem" --x509keyfile "${srcdir}/dsa.1024.pem" >/dev/null 2>&1 &
+PID=$!
+wait_server "${PID}"
 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 1024 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 1024 key and TLS 1.2!"
 
 echo "Checking server DSA-1024 with client DSA-1024 and TLS 1.2"
 
 #try with client key of 1024 bits (should succeed) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.1024.pem --x509keyfile $srcdir/dsa.1024.pem </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 1024 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.1024.pem" --x509keyfile "${srcdir}/dsa.1024.pem" </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 1024 key and TLS 1.2!"
 
 echo "Checking server DSA-1024 with client DSA-2048 and TLS 1.2"
 
 #try with client key of 2048 bits (should succeed) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.2048.pem --x509keyfile $srcdir/dsa.2048.pem </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with a client DSA 2048 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.2048.pem" --x509keyfile "${srcdir}/dsa.2048.pem" </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with a client DSA 2048 key and TLS 1.2!"
 
 echo "Checking server DSA-1024 with client DSA-3072 and TLS 1.2"
 
 #try with client key of 3072 bits (should succeed) 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure --x509certfile $srcdir/cert.dsa.3072.pem --x509keyfile $srcdir/dsa.3072.pem </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with a client DSA 3072 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure --x509certfile "${srcdir}/cert.dsa.3072.pem" --x509keyfile "${srcdir}/dsa.3072.pem" </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with a client DSA 3072 key and TLS 1.2!"
 
-
-kill $PID
+kill "${PID}"
 wait
 
 # DSA 2048 + TLS 1.0
 
 #echo "Checking DSA-2048 with TLS 1.0"
 
-#launch_server $$  --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0" --x509certfile $srcdir/cert.dsa.2048.pem --x509keyfile $srcdir/dsa.2048.pem >/dev/null 2>&1 & PID=$!
-#wait_server $PID
+#launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0" --x509certfile "${srcdir}/cert.dsa.2048.pem" --x509keyfile "${srcdir}/dsa.2048.pem" >/dev/null 2>&1 &
+#PID=$!
+#wait_server "${PID}"
 
-#$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null 2>&1 && \
-#  fail $PID "Succeeded connection to a server with DSA 2048 key and TLS 1.0. Should have failed!"
+#"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null 2>&1 && \
+# fail "${PID}" "Succeeded connection to a server with DSA 2048 key and TLS 1.0. Should have failed!"
 
-#kill $PID
+#kill "${PID}"
 #wait
 
 # DSA 2048 + TLS 1.2
 
 echo "Checking DSA-2048 with TLS 1.2"
 
-launch_server $$  --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile $srcdir/cert.dsa.2048.pem --x509keyfile $srcdir/dsa.2048.pem >/dev/null 2>&1 & PID=$!
-wait_server $PID
+launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile "${srcdir}/cert.dsa.2048.pem" --x509keyfile "${srcdir}/dsa.2048.pem" >/dev/null 2>&1 &
+PID=$!
+wait_server "${PID}"
 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 2048 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 2048 key and TLS 1.2!"
 
-kill $PID
+kill "${PID}"
 wait
 
 # DSA 3072 + TLS 1.0
 
 #echo "Checking DSA-3072 with TLS 1.0"
 
-#launch_server $$  --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0" --x509certfile $srcdir/cert.dsa.3072.pem --x509keyfile $srcdir/dsa.3072.pem >/dev/null 2>&1 & PID=$!
-#wait_server $PID
+#launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0" --x509certfile "${srcdir}/cert.dsa.3072.pem" --x509keyfile "${srcdir}/dsa.3072.pem" >/dev/null 2>&1 &
+#PID=$!
+#wait_server "${PID}"
 #
-#$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null 2>&1 && \
-#  fail $PID "Succeeded connection to a server with DSA 3072 key and TLS 1.0. Should have failed!"
+#"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null 2>&1 && \
+#	fail "${PID}" "Succeeded connection to a server with DSA 3072 key and TLS 1.0. Should have failed!"
 #
-#kill $PID
+#kill "${PID}"
 #wait
 
 # DSA 3072 + TLS 1.2
 
 echo "Checking DSA-3072 with TLS 1.2"
 
-launch_server $$  --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile $srcdir/cert.dsa.3072.pem --x509keyfile $srcdir/dsa.3072.pem >/dev/null 2>&1 & PID=$!
-wait_server $PID
+launch_server $$ --priority "NORMAL:-VERS-TLS-ALL:+VERS-TLS1.2:+DHE-DSS:+SIGN-DSA-SHA256:+SIGN-DSA-SHA1" --x509certfile "${srcdir}/cert.dsa.3072.pem" --x509keyfile "${srcdir}/dsa.3072.pem" >/dev/null 2>&1 &
+PID=$!
+wait_server "${PID}"
 
-$CLI $DEBUG $PRIO -p $PORT 127.0.0.1 --insecure </dev/null >/dev/null || \
-  fail $PID "Failed connection to a server with DSA 3072 key and TLS 1.2!"
+"${CLI}" ${DEBUG} ${PRIO} -p "${PORT}" 127.0.0.1 --insecure </dev/null >/dev/null || \
+	fail "${PID}" "Failed connection to a server with DSA 3072 key and TLS 1.2!"
 
-kill $PID
+kill "${PID}"
 wait
 
 exit 0
-
