tests: added check for import of RSA-PSS key with invalid salt
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>

diff --git a/tests/key-tests/illegal-rsa b/tests/key-tests/illegal-rsa
--- a/tests/key-tests/illegal-rsa
+++ b/tests/key-tests/illegal-rsa
@@ -49,6 +49,15 @@ if test "${rc}" != "1"; then
 	exit ${rc}
 fi
 
+#check invalid RSA pem key. The key has too large salt.
+${VALGRIND} "${CERTTOOL}" -k --infile "${srcdir}/data/key-illegal-rsa-pss.pem"
+rc=$?
+# We're done.
+if test "${rc}" != "1"; then
+	echo "Error in importing illegal RSA-PSS key"
+	exit ${rc}
+fi
+
 rm -f $TMPFILE
 
 exit 0
