tests: converted FIPS140-2 mode checks in Makefiles to run-time in scripts
Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>

diff --git a/tests/key-tests/pkcs8-decode b/tests/key-tests/pkcs8-decode
--- a/tests/key-tests/pkcs8-decode
+++ b/tests/key-tests/pkcs8-decode
@@ -29,6 +29,11 @@ if ! test -x "${CERTTOOL}"; then
 	exit 77
 fi
 
+if test "${GNUTLS_FORCE_FIPS_MODE}" = 1;then
+	echo "Cannot run in FIPS140-2 mode"
+	exit 77
+fi
+
 if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
