tests: suite: cleanup shell usage
Add quotes for most usages of variables.

Added ${} for variables.

Cleanup indentation to be consistent with other tests.

Fix separate builddir issues.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

diff --git a/tests/suite/testdane b/tests/suite/testdane
--- a/tests/suite/testdane
+++ b/tests/suite/testdane
@@ -19,64 +19,64 @@
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
 srcdir="${srcdir:-.}"
-DANETOOL="${DANETOOL:-../../src/danetool$EXEEXT}"
+DANETOOL="${DANETOOL:-../../src/danetool${EXEEXT}}"
 unset RETCODE
 
 # Unfortunately it is extremely fragile and fails 99% of the
 # time.
 if test "${WINDIR}" != "";then
   exit 77
-fi 
+fi
 
-. $srcdir/../scripts/common.sh
+. "${srcdir}/../scripts/common.sh"
 
 # Fine hosts
 
 echo ""
 echo "*** Testing good HTTPS hosts ***"
-# www.vulcano.cl dane.nox.su 
+# www.vulcano.cl dane.nox.su
 HOSTS="good.dane.verisignlabs.com www.freebsd.org www.kumari.net torproject.org fedoraproject.org"
-HOSTS="$HOSTS nohats.ca"
-for i in $HOSTS;do
-echo -n "$i: "
+HOSTS="${HOSTS} nohats.ca"
+for host in ${HOSTS};do
+  echo -n "${host}: "
 
-$DANETOOL --check $i >/dev/null 2>&1
-if [ $? != 0 ];then
-	echo "Error checking $i"
-	exit 1
-fi
-echo "ok"
+  "${DANETOOL}" --check "${host}" >/dev/null 2>&1
+  if [ $? != 0 ];then
+    echo "Error checking ${host}"
+    exit 1
+  fi
+  echo "ok"
 done
 
 echo ""
 echo "*** Testing good SMTP hosts ***"
 #HOSTS="dougbarton.us nlnetlabs.nl"
 HOSTS="nlnetlabs.nl"
-for i in $HOSTS;do
-echo -n "$i: "
+for host in ${HOSTS};do
+  echo -n "${host}: "
 
-$DANETOOL --check $i --port 25 >/dev/null 2>&1
-if [ $? != 0 ];then
-	echo "Error checking $i"
-	exit 1
-fi
-echo "ok"
+  "${DANETOOL}" --check "${host}" --port 25 >/dev/null 2>&1
+  if [ $? != 0 ];then
+    echo "Error checking ${host}"
+    exit 1
+  fi
+  echo "ok"
 done
 
 echo ""
 echo "*** Testing bad HTTPS hosts ***"
 # Not ok
-# used to work: dane-broken.rd.nic.fr 
+# used to work: dane-broken.rd.nic.fr
 HOSTS="bad-hash.dane.verisignlabs.com bad-params.dane.verisignlabs.com"
-HOSTS="$HOSTS bad-sig.dane.verisignlabs.com"
-for i in $HOSTS;do
-echo -n "$i: "
-$DANETOOL --check $i >/dev/null 2>&1
-if [ $? = 0 ];then
-	echo "Checking $i should have failed"
-	exit 1
-fi
-echo "ok"
+HOSTS="${HOSTS} bad-sig.dane.verisignlabs.com"
+for host in ${HOSTS};do
+  echo -n "${host}: "
+  "${DANETOOL}" --check "${host}" >/dev/null 2>&1
+  if [ $? = 0 ];then
+    echo "Checking ${host} should have failed"
+    exit 1
+  fi
+  echo "ok"
 done
 
 
diff --git a/tests/suite/testrng b/tests/suite/testrng
--- a/tests/suite/testrng
+++ b/tests/suite/testrng
@@ -29,7 +29,7 @@ VERSION=`dieharder -l|grep version|cut -d ' ' -f 6`
 if test "$1" = "full";then
   OPTIONS="-a"
 else
-  if test "$VERSION" = "2.28.1";then
+  if test "${VERSION}" = "2.28.1";then
     OPTIONS="-d 5"
     OPTIONS2="-d 10"
   else
@@ -42,122 +42,122 @@ OUTFILE=rng.log
 RNGFILE=rng.out
 RNGFILE2=rng2.out
 
-rm -f $OUTFILE
-rm -f $RNGFILE
-rm -f $RNGFILE2
+rm -f "${OUTFILE}"
+rm -f "${RNGFILE}"
+rm -f "${RNGFILE2}"
 
-. $srcdir/../scripts/common.sh
+. "${srcdir}/../scripts/common.sh"
 
 
 RINPUTNO=`dieharder -g -1|grep file_input_raw|cut -d '|' -f 2|cut -d ' ' -f 1`
 
-if test -z "$RINPUTNO";then
-	echo "Cannot determine dieharder option for raw file input, assuming 201"
-	RINPUTNO=201
+if test -z "${RINPUTNO}";then
+  echo "Cannot determine dieharder option for raw file input, assuming 201"
+  RINPUTNO=201
 fi
 
 echo ""
 echo "Testing nonce PRNG"
 
-./rng nonce 64 $RNGFILE
-./rng nonce 64 $RNGFILE2
-cmp $RNGFILE $RNGFILE2  >/dev/null 2>&1
+./rng nonce 64 "${RNGFILE}"
+./rng nonce 64 "${RNGFILE2}"
+cmp "${RNGFILE}" "${RNGFILE2}"  >/dev/null 2>&1
 ret=$?
 
-if test $ret = 0;then
-	echo "numbers are repeated in nonce!"
-	exit 1
+if test ${ret} = 0;then
+  echo "numbers are repeated in nonce!"
+  exit 1
 fi
 
-./rng nonce 100000000 $RNGFILE
+./rng nonce 100000000 "${RNGFILE}"
 
-dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS >$OUTFILE 2>&1
-if ! test -z "$OPTIONS2";then
-	dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS2 >>$OUTFILE 2>&1
+dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}";then
+  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
-grep FAILED $OUTFILE >/dev/null 2>&1
+grep FAILED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "$ret" = "0";then
-	echo "test failed for nonce"
-	exit 1
+if test "${ret}" = "0";then
+  echo "test failed for nonce"
+  exit 1
 fi
 
-grep PASSED $OUTFILE >/dev/null 2>&1
+grep PASSED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "$ret" != "0";then
-	echo "could not run dieharder test?"
-	exit 1
+if test "${ret}" != "0";then
+  echo "could not run dieharder test?"
+  exit 1
 fi
 
-cat $OUTFILE
-rm -f $OUTFILE
+cat "${OUTFILE}"
+rm -f "${OUTFILE}"
 echo ""
 echo "Testing key PRNG"
 
-./rng key 64 $RNGFILE
-./rng key 64 $RNGFILE2
-cmp $RNGFILE $RNGFILE2 >/dev/null 2>&1
+./rng key 64 "${RNGFILE}"
+./rng key 64 "${RNGFILE2}"
+cmp "${RNGFILE}" "${RNGFILE2}" >/dev/null 2>&1
 ret=$?
 
-if test $ret = 0;then
-	echo "numbers are repeated in nonce!"
-	exit 1
+if test ${ret} = 0;then
+  echo "numbers are repeated in nonce!"
+  exit 1
 fi
 
-./rng key 100000000 $RNGFILE
+./rng key 100000000 "${RNGFILE}"
 
-dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS >$OUTFILE 2>&1
-if ! test -z "$OPTIONS2";then
-	dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS2 >>$OUTFILE 2>&1
+dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}";then
+  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
-grep FAILED $OUTFILE >/dev/null 2>&1 
+grep FAILED "${OUTFILE}" >/dev/null 2>&1 
 ret=$?
 
 
-if test "$ret" = "0";then
-	echo "test failed for key"
-	exit 1
+if test "${ret}" = "0";then
+  echo "test failed for key"
+  exit 1
 fi
 
-grep PASSED $OUTFILE >/dev/null 2>&1
+grep PASSED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "$ret" != "0";then
-	echo "could not run dieharder test?"
-	exit 1
+if test "${ret}" != "0";then
+  echo "could not run dieharder test?"
+  exit 1
 fi
 
-cat $OUTFILE
-rm -f $OUTFILE
+cat "${OUTFILE}"
+rm -f "${OUTFILE}"
 echo ""
 echo "Testing /dev/zero PRNG"
-dd if=/dev/zero of=$RNGFILE bs=4 count=10000000 >/dev/null 2>&1
+dd if=/dev/zero of="${RNGFILE}" bs=4 count=10000000 >/dev/null 2>&1
 
-dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS >$OUTFILE 2>&1
-if ! test -z "$OPTIONS2";then
-	dieharder -f $RNGFILE -g $RINPUTNO $OPTIONS2 >>$OUTFILE 2>&1
+dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}";then
+  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
-grep PASSED $OUTFILE >/dev/null 2>&1 
+grep PASSED "${OUTFILE}" >/dev/null 2>&1 
 ret=$?
 
-if test "$ret" = "0";then
-	echo "test succeeded for /dev/zero!!!"
-	exit 1
+if test "${ret}" = "0";then
+  echo "test succeeded for /dev/zero!!!"
+  exit 1
 fi
 
-grep FAILED $OUTFILE >/dev/null 2>&1
+grep FAILED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "$ret" != "0";then
-	echo "could not run dieharder test?"
-	exit 1
+if test "${ret}" != "0";then
+  echo "could not run dieharder test?"
+  exit 1
 fi
 
-cat $OUTFILE
-rm -f $OUTFILE
-rm -f $RNGFILE
-rm -f $RNGFILE2
+cat "${OUTFILE}"
+rm -f "${OUTFILE}"
+rm -f "${RNGFILE}"
+rm -f "${RNGFILE2}"
 
 exit 0
