fixed polarssl compatibility checks on debian

diff --git a/tests/suite/testcompat-main-polarssl b/tests/suite/testcompat-main-polarssl
--- a/tests/suite/testcompat-main-polarssl
+++ b/tests/suite/testcompat-main-polarssl
@@ -35,7 +35,11 @@ fi
 . $srcdir/../scripts/common.sh
 
 PORT="${PORT:-$RPORT}"
+if test -x /usr/bin/polarssl_ssl_client2;then
+POLARSSL_CLI="/usr/bin/polarssl_ssl_client2"
+else
 POLARSSL_CLI="/usr/libexec/polarssl/ssl_client2"
+fi
 
 TXT=`$CLI --priority NORMAL --list|grep SECP224`
 if test -z $TEXT;then
@@ -44,20 +48,20 @@ else
 	ALL_CURVES=1
 fi
 
-VERSION=`grep released /usr/share/doc/polarssl/ChangeLog|head -1|cut -d ' ' -f 3`
 
-echo "Compatibility checks using polarssl "$VERSION
-echo $VERSION|grep -e 1\.3\. >/dev/null 2>&1
-SV=$?
-if test $SV != 0;then
+echo "Compatibility checks using polarssl"
+
+if ! test -x $POLARSSL_CLI;then
+  echo "PolarSSL is required for this test to run"
+  exit 77
+fi
+
+$POLARSSL_CLI >/dev/null 2>&1
+if test $? = 0;then
   echo "PolarSSL 1.3.x is required for the tests to run"
   exit 77
 fi
 
-if ! test -x $POLARSSL;then
-  echo "PolarSSL is required for this test to run"
-  exit 77
-fi
 
 . ./testcompat-common
 
