updated danetool

diff --git a/tests/suite/testdane b/tests/suite/testdane
--- a/tests/suite/testdane
+++ b/tests/suite/testdane
@@ -29,9 +29,35 @@ fi
 
 . $srcdir/../scripts/common.sh
 
-echo "*** Testing bad hosts"
+# Fine hosts
+
+echo ""
+echo "*** Testing good hosts ***"
+HOSTS="good.dane.verisignlabs.com www.kumari.net torproject.org"
+HOSTS="$HOSTS nohats.ca"
+# used to work: dane.nox.su torproject.org jhcloos.com
+for i in $HOSTS;do
+echo -n "$i: "
+rm -f tmp
+$CLI $i -p 443 --print-cert --insecure >tmp 2>&1 </dev/null
+if [ $? != 0 ];then
+	echo "Error connecting to $i"
+	exit 1
+fi
+
+$DANETOOL --load-certificate tmp --check $i >/dev/null 2>&1
+if [ $? != 0 ];then
+	echo "Error checking $i"
+	exit 1
+fi
+echo "ok"
+done
+
+
+echo "*** Testing bad hosts ***"
 # Not ok
-HOSTS="bad-hash.dane.verisignlabs.com dane-broken.rd.nic.fr bad-params.dane.verisignlabs.com"
+# used to work: dane-broken.rd.nic.fr 
+HOSTS="bad-hash.dane.verisignlabs.com bad-params.dane.verisignlabs.com"
 HOSTS="$HOSTS bad-sig.dane.verisignlabs.com"
 for i in $HOSTS;do
 echo -n "$i: "
@@ -45,31 +71,6 @@ fi
 $DANETOOL --load-certificate tmp --check $i >/dev/null 2>&1
 if [ $? = 0 ];then
 	echo "Checking $i should have failed"
-	exit 1
-fi
-echo "ok"
-done
-
-# Fine hosts
-
-echo ""
-echo "*** Testing good hosts"
-HOSTS="torproject.org jhcloos.com good.dane.verisignlabs.com \
-www.kumari.net"
-HOSTS="$HOSTS nohats.ca"
-# dane.nox.su
-for i in $HOSTS;do
-echo -n "$i: "
-rm -f tmp
-$CLI $i -p 443 --print-cert --insecure >tmp 2>&1 </dev/null
-if [ $? != 0 ];then
-	echo "Error connecting to $i"
-	exit 1
-fi
-
-$DANETOOL --load-certificate tmp --check $i >/dev/null 2>&1
-if [ $? != 0 ];then
-	echo "Error checking $i"
 	exit 1
 fi
 echo "ok"
