added test suite for overriden digests and MACs

diff --git a/tests/slow/override-ciphers b/tests/slow/override-ciphers
--- a/tests/slow/override-ciphers
+++ b/tests/slow/override-ciphers
@@ -39,4 +39,16 @@ if test $? != 0;then
 	exit 1
 fi
 
+GNUTLS_NO_EXPLICIT_INIT=1 $VALGRIND ./mac-override
+if test $? != 0;then
+	echo "overriden mac tests failed"
+	exit 1
+fi
+
+$VALGRIND ./mac-override
+if test $? != 0;then
+	echo "overriden mac tests 2 failed"
+	exit 1
+fi
+
 exit 0
