tests: override-ciphers will not run mac tests on windows
There is some issue with symbols for self tests not being exported.

diff --git a/tests/slow/override-ciphers b/tests/slow/override-ciphers
--- a/tests/slow/override-ciphers
+++ b/tests/slow/override-ciphers
@@ -47,18 +47,23 @@ if test $ret != 0; then
 	exit $ret
 fi
 
-GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./mac-override
-ret=$?
-if test $ret != 0; then
-	echo "overriden mac tests failed"
-	exit $ret
-fi
 
-${VALGRIND} ./mac-override
-ret=$?
-if test $ret != 0; then
-	echo "overriden mac tests 2 failed"
-	exit $ret
+if test "$WINDOWS" = 1;then
+	exit 77
+else
+	GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./mac-override
+	ret=$?
+	if test $ret != 0; then
+		echo "overriden mac tests failed"
+		exit $ret
+	fi
+
+	${VALGRIND} ./mac-override
+	ret=$?
+	if test $ret != 0; then
+		echo "overriden mac tests 2 failed"
+		exit $ret
+	fi
 fi
 
 exit 0
