tests: misc: cleanup shell usage
Add quotes for most usages of variables.

Added ${} for variables.

Cleanup indentation to be consistent with other tests.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

diff --git a/tests/pkcs1-padding/pkcs1-pad b/tests/pkcs1-padding/pkcs1-pad
--- a/tests/pkcs1-padding/pkcs1-pad
+++ b/tests/pkcs1-padding/pkcs1-pad
@@ -23,33 +23,33 @@
 
 set -e
 
-srcdir=${srcdir:-.}
-CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
+srcdir="${srcdir:-.}"
+CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 
 # Check for datefudge
 TSTAMP=`datefudge "2006-09-23" date -u +%s || true`
-if test "$TSTAMP" != "1158962400"; then
-    echo "You need datefudge to run this test"
-    exit 77
+if test "${TSTAMP}" != "1158962400"; then
+  echo "You need datefudge to run this test"
+  exit 77
 fi
 
 # Test 1, PKCS#1 pad digestAlgorithm.parameters
 
 EXPECT1=2002
 
-datefudge "2006-09-23" $CERTTOOL --verify-chain --infile $srcdir/pkcs1-pad-ok.pem | tee out1 >/dev/null 2>&1
-datefudge "2006-09-23" $CERTTOOL --verify-chain --infile $srcdir/pkcs1-pad-broken.pem | tee out2 >/dev/null 2>&1
+datefudge "2006-09-23" "${CERTTOOL}" --verify-chain --infile "${srcdir}/pkcs1-pad-ok.pem" | tee out1 >/dev/null 2>&1
+datefudge "2006-09-23" "${CERTTOOL}" --verify-chain --infile "${srcdir}/pkcs1-pad-broken.pem" | tee out2 >/dev/null 2>&1
 
 out1oks=`grep 'Verified.' out1 | wc -l | tr -d " "`
 out2oks=`grep 'Verified.' out2 | wc -l | tr -d " "`
 out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 out2fails=`grep 'Not verified.' out2 | wc -l | tr -d " "`
 
-if test "$out1oks$out2oks$out1fails$out2fails" != "$EXPECT1"; then
-    echo out1 oks $out1oks fails $out1fails out2 oks $out2oks fails $out2fails
-    echo expected $EXPECT1
-    echo "PKCS1-PAD1 FAIL"
-    exit 1
+if test "${out1oks}${out2oks}${out1fails}${out2fails}" != "${EXPECT1}"; then
+  echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
+  echo "expected ${EXPECT1}"
+  echo "PKCS1-PAD1 FAIL"
+  exit 1
 fi
 
 rm -f out1 out2
@@ -60,19 +60,19 @@ echo "PKCS1-PAD1 OK"
 
 EXPECT2=2002
 
-datefudge "2006-09-23" $CERTTOOL --verify-chain --infile $srcdir/pkcs1-pad-ok2.pem | tee out1 >/dev/null 2>&1
-datefudge "2006-09-23" $CERTTOOL --verify-chain --infile $srcdir/pkcs1-pad-broken2.pem | tee out2 >/dev/null 2>&1
+datefudge "2006-09-23" "${CERTTOOL}" --verify-chain --infile "${srcdir}/pkcs1-pad-ok2.pem" | tee out1 >/dev/null 2>&1
+datefudge "2006-09-23" "${CERTTOOL}" --verify-chain --infile "${srcdir}/pkcs1-pad-broken2.pem" | tee out2 >/dev/null 2>&1
 
 out1oks=`grep 'Verified.' out1 | wc -l | tr -d " "`
 out2oks=`grep 'Verified.' out2 | wc -l | tr -d " "`
 out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 out2fails=`grep 'Not verified.' out2 | wc -l | tr -d " "`
 
-if test "$out1oks$out2oks$out1fails$out2fails" != "$EXPECT2"; then
-    echo out1 oks $out1oks fails $out1fails out2 oks $out2oks fails $out2fails
-    echo expected $EXPECT2
-    echo "PKCS1-PAD2 FAIL"
-    exit 1
+if test "${out1oks}${out2oks}${out1fails}${out2fails}" != "${EXPECT2}"; then
+  echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
+  echo "expected ${EXPECT2}"
+  echo "PKCS1-PAD2 FAIL"
+  exit 1
 fi
 
 rm -f out1 out2
@@ -85,16 +85,16 @@ echo "PKCS1-PAD2 OK"
 
 EXPECT3=02
 
-datefudge "2006-09-23" $CERTTOOL --verify-chain --infile $srcdir/pkcs1-pad-broken3.pem | tee out1 >/dev/null 2>&1
+datefudge "2006-09-23" "${CERTTOOL}" --verify-chain --infile "${srcdir}/pkcs1-pad-broken3.pem" | tee out1 >/dev/null 2>&1
 
 out1oks=`grep 'Verified.' out1 | wc -l | tr -d " "`
 out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 
-if test "$out1oks$out1fails" != "$EXPECT3"; then
-    echo out1 oks $out1oks fails $out1fails
-    echo expected $EXPECT3
-    echo "PKCS1-PAD3 FAIL"
-    exit 1
+if test "${out1oks}${out1fails}" != "${EXPECT3}"; then
+  echo "out1 oks ${out1oks} fails ${out1fails}"
+  echo "expected ${EXPECT3}"
+  echo "PKCS1-PAD3 FAIL"
+  exit 1
 fi
 
 rm -f out1
diff --git a/tests/slow/override-ciphers b/tests/slow/override-ciphers
--- a/tests/slow/override-ciphers
+++ b/tests/slow/override-ciphers
@@ -20,41 +20,39 @@
 # along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
-srcdir="${srcdir:-.}"
-CLI="${CLI:-../../src/gnutls-cli$EXEEXT}"
 unset RETCODE
 if ! test -z "${VALGRIND}";then
-VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
-GNUTLS_NO_EXPLICIT_INIT=1 $VALGRIND ./cipher-override
+GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./cipher-override
 if test $? != 0;then
-	echo "overriden cipher tests failed"
-	exit 1
+  echo "overriden cipher tests failed"
+  exit 1
 fi
 
-$VALGRIND ./cipher-override
+${VALGRIND} ./cipher-override
 if test $? != 0;then
-	echo "overriden cipher tests 2 failed"
-	exit 1
+  echo "overriden cipher tests 2 failed"
+  exit 1
 fi
 
-$VALGRIND ./cipher-override2
+${VALGRIND} ./cipher-override2
 if test $? != 0;then
-	echo "overriden cipher tests 3 failed"
-	exit 1
+  echo "overriden cipher tests 3 failed"
+  exit 1
 fi
 
-GNUTLS_NO_EXPLICIT_INIT=1 $VALGRIND ./mac-override
+GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./mac-override
 if test $? != 0;then
-	echo "overriden mac tests failed"
-	exit 1
+  echo "overriden mac tests failed"
+  exit 1
 fi
 
-$VALGRIND ./mac-override
+${VALGRIND} ./mac-override
 if test $? != 0;then
-	echo "overriden mac tests 2 failed"
-	exit 1
+  echo "overriden mac tests 2 failed"
+  exit 1
 fi
 
 exit 0
diff --git a/tests/slow/test-ciphers b/tests/slow/test-ciphers
--- a/tests/slow/test-ciphers
+++ b/tests/slow/test-ciphers
@@ -20,59 +20,57 @@
 # along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
-srcdir="${srcdir:-.}"
-CLI="${CLI:-../../src/gnutls-cli$EXEEXT}"
 unset RETCODE
 if ! test -z "${VALGRIND}";then
-VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 ./cipher-test
 if test $? != 0;then
-	echo "default cipher tests failed"
-	exit 1
+  echo "default cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x1 ./cipher-test
 if test $? != 0;then
-	echo "included cipher tests failed"
-	exit 1
+  echo "included cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x2 ./cipher-test
 if test $? != 0;then
-	echo "AESNI cipher tests failed"
-	exit 1
+  echo "AESNI cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x4 ./cipher-test
 if test $? != 0;then
-	echo "SSSE3 cipher tests failed"
-	exit 1
+  echo "SSSE3 cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x8 ./cipher-test
 if test $? != 0;then
-	echo "PCLMUL cipher tests failed"
-	exit 1
+  echo "PCLMUL cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x100000 ./cipher-test
 if test $? != 0;then
-	echo "padlock cipher tests failed"
-	exit 1
+  echo "padlock cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x200000 ./cipher-test
 if test $? != 0;then
-	echo "padlock PHE cipher tests failed"
-	exit 1
+  echo "padlock PHE cipher tests failed"
+  exit 1
 fi
 
 GNUTLS_CPUID_OVERRIDE=0x400000 ./cipher-test
 if test $? != 0;then
-	echo "padlock PHE SHA512 cipher tests failed"
-	exit 1
+  echo "padlock PHE SHA512 cipher tests failed"
+  exit 1
 fi
 
 exit 0
diff --git a/tests/userid/userid b/tests/userid/userid
--- a/tests/userid/userid
+++ b/tests/userid/userid
@@ -20,15 +20,15 @@
 # along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
-srcdir=${srcdir:-.}
-CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
+srcdir="${srcdir:-.}"
+CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 
-$CERTTOOL --certificate-info --infile $srcdir/userid.pem >out 2>&1
+$CERTTOOL --certificate-info --infile "${srcdir}/userid.pem" >out 2>&1
 RET=$?
-if [ $RET !=  0 ];then
-	echo "Error in userid:"
-	cat out
-	exit 1
+if [ ${RET} !=  0 ];then
+  echo "Error in userid:"
+  cat out
+  exit 1
 fi
 
 rm -f out
