tests: tab indent + minor style changes
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

diff --git a/tests/cert-tests/aki b/tests/cert-tests/aki
--- a/tests/cert-tests/aki
+++ b/tests/cert-tests/aki
@@ -25,17 +25,17 @@ set -e
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/aki-cert.pem" \
-  |grep -v "Algorithm Security Level" > tmp-aki.pem
+	|grep -v "Algorithm Security Level" > tmp-aki.pem
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "info failed"
-  exit ${rc}
+	echo "info failed"
+	exit ${rc}
 fi
 
 
@@ -44,7 +44,7 @@ rc=$?
 
 # We're done.
 if test "${rc}" != "0"; then
-  exit ${rc}
+	exit ${rc}
 fi
 
 rm -f tmp-aki.pem
diff --git a/tests/cert-tests/crq b/tests/cert-tests/crq
--- a/tests/cert-tests/crq
+++ b/tests/cert-tests/crq
@@ -25,8 +25,8 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
 OUTFILE=out.tmp
 
@@ -35,14 +35,14 @@ rc=$?
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Invalid crq decoding failed"
-  exit ${rc}
+	echo "Invalid crq decoding failed"
+	exit ${rc}
 fi
 
 grep "error: get_key_id" "${OUTFILE}" >/dev/null 2>&1
 if test "$?" != "0"; then
-  echo "crq decoding didn't fail as expected"
-  exit 1
+	echo "crq decoding didn't fail as expected"
+	exit 1
 fi
 
 rm -f "${OUTFILE}"
diff --git a/tests/cert-tests/email b/tests/cert-tests/email
--- a/tests/cert-tests/email
+++ b/tests/cert-tests/email
@@ -23,72 +23,72 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF=$"{DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.exclude.test.example.com" --verify-email test@example.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 1 failed"
-  exit 1
+	echo "email test 1 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.exclude.test.example.com" --verify-email invalid@example.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 2 failed"
-  exit 1
+	echo "email test 2 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.test.example.com" --verify-email test@example.com
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "email test 3 failed"
-  exit 1
+	echo "email test 3 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.test.example.com" --verify-email invalid@example.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 4 failed"
-  exit 1
+	echo "email test 4 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.invalid.example.com" --verify-email invalid@example.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 5 failed"
-  exit 1
+	echo "email test 5 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.invalid.example.com" --verify-email test@cola.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 6 failed"
-  exit 1
+	echo "email test 6 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.test.example.com-2" --verify-email test@example.com
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "email test 7 failed"
-  exit 1
+	echo "email test 7 failed"
+	exit 1
 fi
 
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/email-certs/chain.test.example.com-2" --verify-email invalid@example.com
 rc=$?
 
 if test "${rc}" != "1"; then
-  echo "email test 8 failed"
-  exit 1
+	echo "email test 8 failed"
+	exit 1
 fi
 
 
diff --git a/tests/cert-tests/invalid-sig b/tests/cert-tests/invalid-sig
--- a/tests/cert-tests/invalid-sig
+++ b/tests/cert-tests/invalid-sig
@@ -25,8 +25,8 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 #check whether a different PKCS #1 signature than the advertized in certificate is tolerated
@@ -35,8 +35,8 @@ rc=$?
 
 # We're done.
 if test "${rc}" = "0"; then
-  echo "Verification of invalid signature (1) failed"
-  exit ${rc}
+	echo "Verification of invalid signature (1) failed"
+	exit ${rc}
 fi
 
 #check whether a different tbsCertificate than the outer signature algorithm is tolerated
@@ -45,8 +45,8 @@ rc=$?
 
 # We're done.
 if test "${rc}" = "0"; then
-  echo "Verification of invalid signature (2) failed"
-  exit ${rc}
+	echo "Verification of invalid signature (2) failed"
+	exit ${rc}
 fi
 
 #check whether a different tbsCertificate than the outer signature algorithm is tolerated
@@ -55,8 +55,8 @@ rc=$?
 
 # We're done.
 if test "${rc}" = "0"; then
-  echo "Verification of invalid signature (3) failed"
-  exit ${rc}
+	echo "Verification of invalid signature (3) failed"
+	exit ${rc}
 fi
 
 exit 0
diff --git a/tests/cert-tests/pathlen b/tests/cert-tests/pathlen
--- a/tests/cert-tests/pathlen
+++ b/tests/cert-tests/pathlen
@@ -25,26 +25,26 @@ set -e
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/ca-no-pathlen.pem" \
-  |grep -v "Algorithm Security Level" > new-ca-no-pathlen.pem
+	|grep -v "Algorithm Security Level" > new-ca-no-pathlen.pem
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "info 1 failed"
-  exit ${rc}
+	echo "info 1 failed"
+	exit ${rc}
 fi
 
 ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/no-ca-or-pathlen.pem" \
-  |grep -v "Algorithm Security Level" > new-no-ca-or-pathlen.pem
+	|grep -v "Algorithm Security Level" > new-no-ca-or-pathlen.pem
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "info 2 failed"
-  exit ${rc}
+	echo "info 2 failed"
+	exit ${rc}
 fi
 
 ${DIFF} "${srcdir}/ca-no-pathlen.pem" new-ca-no-pathlen.pem
@@ -55,7 +55,7 @@ rc2=$?
 
 # We're done.
 if test "${rc1}" != "0"; then
-  exit ${rc1}
+	exit ${rc1}
 fi
 
 rm -f new-ca-no-pathlen.pem new-no-ca-or-pathlen.pem
diff --git a/tests/cert-tests/pem-decoding b/tests/cert-tests/pem-decoding
--- a/tests/cert-tests/pem-decoding
+++ b/tests/cert-tests/pem-decoding
@@ -25,8 +25,8 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 #check whether "funny" spaces can be interpreted
@@ -35,8 +35,8 @@ rc=$?
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Funny-spacing cert decoding failed 1"
-  exit ${rc}
+	echo "Funny-spacing cert decoding failed 1"
+	exit ${rc}
 fi
 
 #check whether a BMPString attribute can be properly decoded
@@ -44,8 +44,8 @@ ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/bmpstring.pem" 
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "BMPString cert decoding failed 1"
-  exit ${rc}
+	echo "BMPString cert decoding failed 1"
+	exit ${rc}
 fi
 
 #Note that --strip-trailing-cr is used for the test
@@ -54,8 +54,8 @@ ${DIFF} "${srcdir}/bmpstring.pem" tmp-pem.pem || ${DIFF} --strip-trailing-cr "${
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "BMPString cert decoding failed 2"
-  exit ${rc}
+	echo "BMPString cert decoding failed 2"
+	exit ${rc}
 fi
 
 #check whether complex-cert is decoded as expected
@@ -63,8 +63,8 @@ ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/complex-cert.pe
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "Complex cert decoding failed 1"
-  exit ${rc}
+	echo "Complex cert decoding failed 1"
+	exit ${rc}
 fi
 
 cat "${srcdir}/complex-cert.pem" |grep -v "Not After:" >tmp1
@@ -73,8 +73,8 @@ ${DIFF} tmp1 tmp2 || ${DIFF} --strip-trailing-cr tmp1 tmp2
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "Complex cert decoding failed 2"
-  exit ${rc}
+	echo "Complex cert decoding failed 2"
+	exit ${rc}
 fi
 
 #check whether the cert with many othernames is decoded as expected
@@ -82,8 +82,8 @@ ${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/xmpp-othername.
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "XMPP cert decoding failed 1"
-  exit ${rc}
+	echo "XMPP cert decoding failed 1"
+	exit ${rc}
 fi
 
 cat "${srcdir}/xmpp-othername.pem" |grep -v "Not After:" >tmp1
@@ -92,8 +92,8 @@ ${DIFF} tmp1 tmp2 || ${DIFF} --strip-trailing-cr tmp1 tmp2
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "XMPP cert decoding failed 2"
-  exit ${rc}
+	echo "XMPP cert decoding failed 2"
+	exit ${rc}
 fi
 
 rm -f tmp-pem.pem tmp1 tmp2
diff --git a/tests/cert-tests/pkcs7 b/tests/cert-tests/pkcs7
--- a/tests/cert-tests/pkcs7
+++ b/tests/cert-tests/pkcs7
@@ -23,54 +23,54 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
 OUTFILE=out-pkcs7.tmp
 OUTFILE2=out2-pkcs7.tmp
 
-for FILE in single-ca.p7b full.p7b;do
+for FILE in single-ca.p7b full.p7b; do
 ${VALGRIND} "${CERTTOOL}" --inder --p7-info --infile "${srcdir}/${FILE}"|grep -v "Signing time" >"${OUTFILE}"
 rc=$?
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 decoding failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 decoding failed"
+	exit ${rc}
 fi
 
 ${DIFF} "${OUTFILE}" "${srcdir}/${FILE}.out" >/dev/null
 if test "$?" != "0"; then
-  echo "${FILE}: PKCS7 decoding didn't produce the correct file"
-  exit 1
+	echo "${FILE}: PKCS7 decoding didn't produce the correct file"
+	exit 1
 fi
 done
 
 # check signatures
 
-for FILE in full.p7b;do
+for FILE in full.p7b; do
 ${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 verification failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 verification failed"
+	exit ${rc}
 fi
 
 ${VALGRIND} "${CERTTOOL}" --verify-purpose=1.3.6.1.5.5.7.3.1 --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 verification failed with key purpose"
-  exit ${rc}
+	echo "${FILE}: PKCS7 verification failed with key purpose"
+	exit ${rc}
 fi
 
 ${VALGRIND} "${CERTTOOL}" --verify-purpose=1.3.6.1.5.5.7.3.3 --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
 if test "${rc}" = "0"; then
-  echo "${FILE}: PKCS7 verification succeeded with wrong key purpose"
-  exit 2
+	echo "${FILE}: PKCS7 verification succeeded with wrong key purpose"
+	exit 2
 fi
 
 done
@@ -82,16 +82,16 @@ ${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/.
 rc=$?
 
 if test "${rc}" = "0"; then
-  echo "${FILE}: PKCS7 verification succeeded without providing detached data"
-  exit 2
+	echo "${FILE}: PKCS7 verification succeeded without providing detached data"
+	exit 2
 fi
 
 ${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-data "${srcdir}/pkcs7-detached.txt" --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}"
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 verification failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 verification failed"
+	exit ${rc}
 fi
 
 # Test cert combination
@@ -102,14 +102,14 @@ ${VALGRIND} "${CERTTOOL}" --p7-generate --load-certificate "${OUTFILE2}" >"${OUT
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct generation failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct generation failed"
+	exit ${rc}
 fi
 
 ${DIFF} "${OUTFILE}" "${srcdir}/p7-combined.out" >/dev/null
 if test "$?" != "0"; then
-  echo "${FILE}: PKCS7 generation didn't produce the correct file"
-  exit 1
+	echo "${FILE}: PKCS7 generation didn't produce the correct file"
+	exit 1
 fi
 
 # Test signing
@@ -118,8 +118,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-sign --load-privkey  "${srcdir}/../../doc/credent
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing failed"
+	exit ${rc}
 fi
 
 FILE="signing-verify"
@@ -127,8 +127,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/cr
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing failed verification"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing failed verification"
+	exit ${rc}
 fi
 
 
@@ -137,8 +137,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-detached-sign --load-privkey  "${srcdir}/../../do
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing-detached failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing-detached failed"
+	exit ${rc}
 fi
 
 FILE="signing-detached-verify"
@@ -146,8 +146,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/cr
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing-detached failed verification"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing-detached failed verification"
+	exit ${rc}
 fi
 
 # Test signing with broken algorithms
@@ -156,8 +156,8 @@ ${VALGRIND} "${CERTTOOL}" --hash md5 --p7-sign --load-privkey  "${srcdir}/../../
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing-broken failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing-broken failed"
+	exit ${rc}
 fi
 
 FILE="signing-verify-broken"
@@ -165,8 +165,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/cr
 rc=$?
 
 if test "${rc}" = "0"; then
-  echo "${FILE}: PKCS7 struct verification succeeded with broken algo"
-  exit 1
+	echo "${FILE}: PKCS7 struct verification succeeded with broken algo"
+	exit 1
 fi
 
 FILE="signing-time"
@@ -174,14 +174,14 @@ ${VALGRIND} "${CERTTOOL}" --p7-detached-sign --p7-time --load-privkey  "${srcdir
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing with time failed"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing with time failed"
+	exit ${rc}
 fi
 
 ${VALGRIND} "${CERTTOOL}" --p7-info <"${OUTFILE}"|grep "Signing time:" "${OUTFILE}" >/dev/null 2>&1
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing with time failed. No time was found."
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing with time failed. No time was found."
+	exit ${rc}
 fi
 
 FILE="signing-time-verify"
@@ -189,8 +189,8 @@ ${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/cr
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "${FILE}: PKCS7 struct signing with time failed verification"
-  exit ${rc}
+	echo "${FILE}: PKCS7 struct signing with time failed verification"
+	exit ${rc}
 fi
 
 rm -f "${OUTFILE}"
diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -29,9 +29,9 @@ export TZ="UTC"
 # Check for datefudge
 TSTAMP=`datefudge "2006-09-23" date -u +%s || true`
 if test "$TSTAMP" != "1158969600"; then
-  echo $TSTAMP
-  echo "You need datefudge to run this test"
-  exit 77
+	echo $TSTAMP
+	echo "You need datefudge to run this test"
+	exit 77
 fi
 
 # Note that in rare cases this test may fail because the
@@ -41,24 +41,23 @@ fi
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-test.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-test.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-test.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-test.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 1 failed"
-  exit ${rc}
+	echo "Test 1 failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -66,24 +65,23 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-utf8.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-utf8.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-utf8.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-utf8.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 2 (UTF8) failed"
-  exit ${rc}
+	echo "Test 2 (UTF8) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -91,38 +89,37 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-dn.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-dn.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-dn.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-dn.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 3 (DN) failed"
-  exit ${rc}
+	echo "Test 3 (DN) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
 
 datefudge "2007-04-22" \
-  "${CERTTOOL}" --generate-self-signed \
-  --load-privkey "${srcdir}/template-test.key" \
-  --template "${srcdir}/template-dn-err.tmpl" \
-  --outfile tmp-tt.pem 2>/dev/null
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-dn-err.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 rc=$?
 
 if test "${rc}" = "0"; then
-  echo "Test 3 (DN-err) failed"
-  exit ${rc}
+	echo "Test 3 (DN-err) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -130,24 +127,23 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-overflow.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-overflow.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-overflow.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-overflow.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 4 (overflow1) failed"
-  exit ${rc}
+	echo "Test 4 (overflow1) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -158,24 +154,23 @@ if echo __SIZEOF_POINTER__ | cpp -E - - | grep '^8$' >/dev/null; then
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-overflow2.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-overflow2.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-overflow2.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-overflow2.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 5 (overflow2) failed"
-  exit ${rc}
+	echo "Test 5 (overflow2) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -184,24 +179,23 @@ fi
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-date.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-date.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-date.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-date.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 6 (explicit dates) failed"
-  exit ${rc}
+	echo "Test 6 (explicit dates) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
@@ -211,53 +205,51 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "${rc}" != "0" -a $counter -le 3 ]
-do
-  datefudge "2007-04-22" \
-    "${CERTTOOL}" --generate-self-signed \
-    --load-privkey "${srcdir}/template-test.key" \
-    --template "${srcdir}/template-nc.tmpl" \
-    --outfile tmp-tt.pem 2>/dev/null
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-nc.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
 
-  ${DIFF} "${srcdir}/template-nc.pem" tmp-tt.pem >/dev/null 2>&1
-  rc=$?
-  test ${rc} != 0 && sleep 3
-  counter=`expr $counter + 1`
+	${DIFF} "${srcdir}/template-nc.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
 done
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "Test 7 (name constraints) failed"
-  exit ${rc}
+	echo "Test 7 (name constraints) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
 
 # Test the GeneralizedTime support
-if test "$(getconf LONG_BIT)" = "64";then
-  # we should test that on systems which have 64-bit time_t.
-  rc=1
-  counter=1
+if test "$(getconf LONG_BIT)" = "64"; then
+	# we should test that on systems which have 64-bit time_t.
+	rc=1
+	counter=1
 
-  while [ "${rc}" != "0" -a $counter -le 3 ]
-  do
-    datefudge "2051-04-22" \
-      "${CERTTOOL}" --generate-self-signed \
-      --load-privkey "${srcdir}/template-test.key" \
-      --template "${srcdir}/template-generalized.tmpl" \
-      --outfile tmp-tt.pem 2>/dev/null
+	while [ "${rc}" != "0" -a $counter -le 3 ]; do
+		datefudge "2051-04-22" \
+			"${CERTTOOL}" --generate-self-signed \
+				--load-privkey "${srcdir}/template-test.key" \
+				--template "${srcdir}/template-generalized.tmpl" \
+				--outfile tmp-tt.pem 2>/dev/null
 
-    ${DIFF} "${srcdir}/template-generalized.pem" tmp-tt.pem >/dev/null 2>&1
-    rc=$?
-    test ${rc} != 0 && sleep 3
-    counter=`expr $counter + 1`
-  done
+		${DIFF} "${srcdir}/template-generalized.pem" tmp-tt.pem >/dev/null 2>&1
+		rc=$?
+		test ${rc} != 0 && sleep 3
+		counter=`expr $counter + 1`
+	done
 
-  # We're done.
-  if test "${rc}" != "0"; then
-    echo "Test 8 (generalizedTime) failed"
-    exit ${rc}
-  fi
+	# We're done.
+	if test "${rc}" != "0"; then
+		echo "Test 8 (generalizedTime) failed"
+		exit ${rc}
+	fi
 fi
 
 rm -f tmp-tt.pem
diff --git a/tests/key-tests/key-id b/tests/key-tests/key-id
--- a/tests/key-tests/key-id
+++ b/tests/key-tests/key-id
@@ -36,14 +36,14 @@ echo "serial = 0" > tmpl
 #    --outfile user-no-keyid.pem 2> /dev/null
 
 eval "${CERTTOOL}" ${PARAMS} --load-ca-certificate "${srcdir}/ca-weird-keyid.pem" \
-    --outfile user-weird-keyid.pem 2> /dev/null
+	--outfile user-weird-keyid.pem 2> /dev/null
 
 if "${CERTTOOL}" -i < user-weird-keyid.pem \
-    | grep '7a2c7a6097460603cbfb28e8e219df18deeb4e0d' > /dev/null; then
+	| grep '7a2c7a6097460603cbfb28e8e219df18deeb4e0d' > /dev/null; then
 :
 else
-  echo "Could not find CA SKI in user certificate."
-  exit 1;
+	echo "Could not find CA SKI in user certificate."
+	exit 1;
 fi
 
 rm -f tmpl user-gnutls-keyid.pem user-no-keyid.pem user-weird-keyid.pem
diff --git a/tests/openpgp-certs/testcerts b/tests/openpgp-certs/testcerts
--- a/tests/openpgp-certs/testcerts
+++ b/tests/openpgp-certs/testcerts
@@ -25,8 +25,8 @@ SERV="${SERV:-../../src/gnutls-serv} -q"
 CLI="${CLI:-../../src/gnutls-cli}"
 DEBUG=""
 
-if test "${WINDIR}" != "";then
-  exit 77
+if test "${WINDIR}" != ""; then
+	exit 77
 fi 
 
 . "${srcdir}/../scripts/common.sh"
@@ -35,7 +35,8 @@ PORT="${PORT:-$RPORT}"
 
 echo "Checking OpenPGP certificate verification"
 
-launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-127.0.0.1-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 & PID=$!
+launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-127.0.0.1-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 &
+PID=$!
 wait_server ${PID}
 
 # give the server a chance to initialize
@@ -47,22 +48,23 @@ wait_server ${PID}
 #  fail "Connection to verified IP address should have succeeded! (error code $?)" $?
 
 "${CLI}" ${DEBUG} -p "${PORT}" 127.0.0.2 --priority NORMAL:+CTYPE-OPENPGP --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "Connection to unrecognized IP address should have failed!"
+	fail ${PID} "Connection to unrecognized IP address should have failed!"
 
 "${CLI}" ${DEBUG} -p "${PORT}" localhost --priority NORMAL:+CTYPE-OPENPGP --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "Connection to unverified (but present) 'localhost' should have failed!"
+	fail ${PID} "Connection to unverified (but present) 'localhost' should have failed!"
 
 kill ${PID}
 wait
 
-launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-localhost-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 & PID=$!
+launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-localhost-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 &
+PID=$!
 wait_server ${PID}
 
 echo | "${CLI}" ${DEBUG} --priority NORMAL:+CTYPE-OPENPGP -p "${PORT}" 127.0.0.1 --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "Connection to unverified IP address should have failed! (error code $?)" $?
+	fail ${PID} "Connection to unverified IP address should have failed! (error code $?)" $?
 
 "${CLI}" ${DEBUG} --priority NORMAL:+CTYPE-OPENPGP -p "${PORT}" 127.0.0.2 --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "Connection to unrecognized IP address should have failed!"
+	fail ${PID} "Connection to unrecognized IP address should have failed!"
 
 #see reason above
 #"${CLI}" -p "${PORT}" localhost --pgpkeyring ca-public.gpg </dev/null >/dev/null || \
@@ -71,15 +73,16 @@ echo | "${CLI}" ${DEBUG} --priority NORMAL:+CTYPE-OPENPGP -p "${PORT}" 127.0.0.1
 kill ${PID}
 wait
 
-launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-all-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 & PID=$!
+launch_server $$ --priority NORMAL:+CTYPE-OPENPGP --pgpcertfile "${srcdir}/srv-public-all-signed.gpg" --pgpkeyfile "${srcdir}/srv-secret.gpg" >/dev/null 2>&1 &
+PID=$!
 wait_server ${PID}
 
 # give the server a chance to initialize
 echo | "${CLI}" ${DEBUG} --priority NORMAL:+CTYPE-OPENPGP -p "${PORT}" 127.0.0.1 --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null || \
-  fail ${PID} "Connection to signed PGP certificate should have succeeded! (error code $?)" $?
+	fail ${PID} "Connection to signed PGP certificate should have succeeded! (error code $?)" $?
 
 "${CLI}" ${DEBUG} --priority NORMAL:+CTYPE-OPENPGP -p "${PORT}" 127.0.0.2 --pgpkeyring "${srcdir}/ca-public.gpg" </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "Connection to unrecognized IP address should have failed!"
+	fail ${PID} "Connection to unrecognized IP address should have failed!"
 
 kill ${PID}
 wait
diff --git a/tests/openpgp-certs/testselfsigs b/tests/openpgp-certs/testselfsigs
--- a/tests/openpgp-certs/testselfsigs
+++ b/tests/openpgp-certs/testselfsigs
@@ -28,26 +28,26 @@ CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 unset RETCODE || true
 
 fail() {
-   echo "Failure: $1" >&2
-   RETCODE=${RETCODE:-${2:-1}}
+	 echo "Failure: $1" >&2
+	 RETCODE=${RETCODE:-${2:-1}}
 }
 
 echo "Checking OpenPGP certificate self verification"
 
 ("${CERTTOOL}" --inraw --pgp-certificate-info --infile "${srcdir}/selfsigs/alice.pub" \
-    | grep "^Self Signature verification: ok" > /dev/null) || \
-    fail "Self sig Verification should have succeeded!"
+	| grep "^Self Signature verification: ok" > /dev/null) || \
+	fail "Self sig Verification should have succeeded!"
 
 ("${CERTTOOL}" --inraw --pgp-certificate-info --infile "${srcdir}/selfsigs/alice-mallory-badsig18.pub" \
-    | grep "^Self Signature verification: failed" > /dev/null) || \
-    fail "Self sig Verification should have failed!"
+	| grep "^Self Signature verification: failed" > /dev/null) || \
+	fail "Self sig Verification should have failed!"
 
 ("${CERTTOOL}" --inraw --pgp-certificate-info --infile "${srcdir}/selfsigs/alice-mallory-irrelevantsig.pub" \
-    | grep "^Self Signature verification: failed" >/dev/null) || \
-    fail "Self sig Verification should have failed!"
+	| grep "^Self Signature verification: failed" >/dev/null) || \
+	fail "Self sig Verification should have failed!"
 
 ("${CERTTOOL}" --inraw --pgp-certificate-info --infile "${srcdir}/selfsigs/alice-mallory-nosig18.pub" \
-    | grep "^Self Signature verification: failed" >/dev/null) || \
-    fail "Self sig Verification should have failed!"
+	| grep "^Self Signature verification: failed" >/dev/null) || \
+	fail "Self sig Verification should have failed!"
 
 exit ${RETCODE:-0}
diff --git a/tests/pkcs1-padding/pkcs1-pad b/tests/pkcs1-padding/pkcs1-pad
--- a/tests/pkcs1-padding/pkcs1-pad
+++ b/tests/pkcs1-padding/pkcs1-pad
@@ -31,8 +31,8 @@ export TZ="UTC"
 # Check for datefudge
 TSTAMP=`datefudge "2006-09-23" date -u +%s || true`
 if test "${TSTAMP}" != "1158969600"; then
-  echo "You need datefudge to run this test"
-  exit 77
+	echo "You need datefudge to run this test"
+	exit 77
 fi
 
 # Test 1, PKCS#1 pad digestAlgorithm.parameters
@@ -48,10 +48,10 @@ out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 out2fails=`grep 'Not verified.' out2 | wc -l | tr -d " "`
 
 if test "${out1oks}${out2oks}${out1fails}${out2fails}" != "${EXPECT1}"; then
-  echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
-  echo "expected ${EXPECT1}"
-  echo "PKCS1-PAD1 FAIL"
-  exit 1
+	echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
+	echo "expected ${EXPECT1}"
+	echo "PKCS1-PAD1 FAIL"
+	exit 1
 fi
 
 rm -f out1 out2
@@ -71,10 +71,10 @@ out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 out2fails=`grep 'Not verified.' out2 | wc -l | tr -d " "`
 
 if test "${out1oks}${out2oks}${out1fails}${out2fails}" != "${EXPECT2}"; then
-  echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
-  echo "expected ${EXPECT2}"
-  echo "PKCS1-PAD2 FAIL"
-  exit 1
+	echo "out1 oks ${out1oks} fails ${out1fails} out2 oks ${out2oks} fails ${out2fails}"
+	echo "expected ${EXPECT2}"
+	echo "PKCS1-PAD2 FAIL"
+	exit 1
 fi
 
 rm -f out1 out2
@@ -93,10 +93,10 @@ out1oks=`grep 'Verified.' out1 | wc -l | tr -d " "`
 out1fails=`grep 'Not verified.' out1 | wc -l | tr -d " "`
 
 if test "${out1oks}${out1fails}" != "${EXPECT3}"; then
-  echo "out1 oks ${out1oks} fails ${out1fails}"
-  echo "expected ${EXPECT3}"
-  echo "PKCS1-PAD3 FAIL"
-  exit 1
+	echo "out1 oks ${out1oks} fails ${out1fails}"
+	echo "expected ${EXPECT3}"
+	echo "PKCS1-PAD3 FAIL"
+	exit 1
 fi
 
 rm -f out1
diff --git a/tests/slow/override-ciphers b/tests/slow/override-ciphers
--- a/tests/slow/override-ciphers
+++ b/tests/slow/override-ciphers
@@ -21,38 +21,38 @@
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
 unset RETCODE
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./cipher-override
-if test $? != 0;then
-  echo "overriden cipher tests failed"
-  exit 1
+if test $? != 0; then
+	echo "overriden cipher tests failed"
+	exit 1
 fi
 
 ${VALGRIND} ./cipher-override
-if test $? != 0;then
-  echo "overriden cipher tests 2 failed"
-  exit 1
+if test $? != 0; then
+	echo "overriden cipher tests 2 failed"
+	exit 1
 fi
 
 ${VALGRIND} ./cipher-override2
-if test $? != 0;then
-  echo "overriden cipher tests 3 failed"
-  exit 1
+if test $? != 0; then
+	echo "overriden cipher tests 3 failed"
+	exit 1
 fi
 
 GNUTLS_NO_EXPLICIT_INIT=1 ${VALGRIND} ./mac-override
-if test $? != 0;then
-  echo "overriden mac tests failed"
-  exit 1
+if test $? != 0; then
+	echo "overriden mac tests failed"
+	exit 1
 fi
 
 ${VALGRIND} ./mac-override
-if test $? != 0;then
-  echo "overriden mac tests 2 failed"
-  exit 1
+if test $? != 0; then
+	echo "overriden mac tests 2 failed"
+	exit 1
 fi
 
 exit 0
diff --git a/tests/suite/chain b/tests/suite/chain
--- a/tests/suite/chain
+++ b/tests/suite/chain
@@ -34,39 +34,39 @@ RET=0
 
 i=1
 while test -d X509tests/test${i}; do
-  find X509tests/test${i} -name *.crl -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --crl-info --inder --infile > chains/chain${i}.pem  2>/dev/null
-  find X509tests/test${i} -name E*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
-  if test "${i}" -gt 1; then
-    find X509tests/test${i} -name I*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
-  fi
-  find X509tests/test${i} -name T*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
-  "${CERTTOOL}" -e --infile chains/chain${i}.pem > out 2>&1
-  rc=$?
-  if test $rc != 0 && test $rc != 1; then
-    echo "Chain ${i} FATAL failure."
-    RET=1
-  else
-    if echo "$KNOWN_BUGS" | grep " ${i} " > /dev/null 2>&1; then
-        echo "Chain ${i} verification was skipped due to known bug."
-    elif echo "$SUCCESS" | grep " ${i} " > /dev/null 2>&1; then
-      if grep 'Chain verification output:' out | grep -v 'Chain verification output: Verified\.' > /dev/null 2>&1; then
-        echo "Chain ${i} verification failure UNEXPECTED."
-        RET=1
-      else
-        echo "Chain ${i} verification success as expected."
-      fi
-    elif echo "$FAILURE" | grep " ${i} " >/dev/null 2>&1; then
-      if grep 'Chain verification output:' out | grep -v 'Chain verification output: Verified\.' > /dev/null 2>&1; then
-        echo "Chain ${i} verification failure as expected."
-      else
-        echo "Chain ${i} verification success UNEXPECTED. "
-        RET=1
-      fi
-    else
-      echo "Chain ${i} unclassified."
-    fi
-  fi
-  i=`expr ${i} + 1`
+	find X509tests/test${i} -name *.crl -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --crl-info --inder --infile > chains/chain${i}.pem  2>/dev/null
+	find X509tests/test${i} -name E*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
+	if test "${i}" -gt 1; then
+		find X509tests/test${i} -name I*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
+	fi
+	find X509tests/test${i} -name T*.crt -print0 |sort -r -z|xargs -n1 --null "${CERTTOOL}" --certificate-info --inder --infile >> chains/chain${i}.pem 2>/dev/null
+	"${CERTTOOL}" -e --infile chains/chain${i}.pem > out 2>&1
+	rc=$?
+	if test $rc != 0 && test $rc != 1; then
+		echo "Chain ${i} FATAL failure."
+		RET=1
+	else
+		if echo "$KNOWN_BUGS" | grep " ${i} " > /dev/null 2>&1; then
+				echo "Chain ${i} verification was skipped due to known bug."
+		elif echo "$SUCCESS" | grep " ${i} " > /dev/null 2>&1; then
+			if grep 'Chain verification output:' out | grep -v 'Chain verification output: Verified\.' > /dev/null 2>&1; then
+				echo "Chain ${i} verification failure UNEXPECTED."
+				RET=1
+			else
+				echo "Chain ${i} verification success as expected."
+			fi
+		elif echo "$FAILURE" | grep " ${i} " >/dev/null 2>&1; then
+			if grep 'Chain verification output:' out | grep -v 'Chain verification output: Verified\.' > /dev/null 2>&1; then
+				echo "Chain ${i} verification failure as expected."
+			else
+				echo "Chain ${i} verification success UNEXPECTED. "
+				RET=1
+			fi
+		else
+			echo "Chain ${i} unclassified."
+		fi
+	fi
+	i=`expr ${i} + 1`
 done
 rm -f out
 
diff --git a/tests/suite/crl-test b/tests/suite/crl-test
--- a/tests/suite/crl-test
+++ b/tests/suite/crl-test
@@ -23,8 +23,8 @@
 srcdir="${srcdir:-.}"
 DIFF="${DIFF:-diff}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
-if ! test -z "${VALGRIND}";then
-  VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+if ! test -z "${VALGRIND}"; then
+	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
 rm -f tmp-long.pem
@@ -33,16 +33,16 @@ rc=$?
 
 # We're done.
 if test "${rc}" != "0"; then
-  echo "CRL decoding failed 1!"
-  exit ${rc}
+	echo "CRL decoding failed 1!"
+	exit ${rc}
 fi
 
 ${DIFF} "${srcdir}/crl/long.pem tmp-long.pem" || ${DIFF} --strip-trailing-cr "${srcdir}/crl/long.pem" tmp-long.pem
 rc=$?
 
 if test "${rc}" != "0"; then
-  echo "CRL decoding failed 2!"
-  exit ${rc}
+	echo "CRL decoding failed 2!"
+	exit ${rc}
 fi
 
 rm -f tmp-long.pem
diff --git a/tests/suite/testdane b/tests/suite/testdane
--- a/tests/suite/testdane
+++ b/tests/suite/testdane
@@ -24,8 +24,8 @@ unset RETCODE
 
 # Unfortunately it is extremely fragile and fails 99% of the
 # time.
-if test "${WINDIR}" != "";then
-  exit 77
+if test "${WINDIR}" != ""; then
+	exit 77
 fi
 
 . "${srcdir}/../scripts/common.sh"
@@ -37,30 +37,30 @@ echo "*** Testing good HTTPS hosts ***"
 # www.vulcano.cl dane.nox.su
 HOSTS="good.dane.verisignlabs.com www.freebsd.org www.kumari.net torproject.org fedoraproject.org"
 HOSTS="${HOSTS} nohats.ca"
-for host in ${HOSTS};do
-  echo -n "${host}: "
+for host in ${HOSTS}; do
+	echo -n "${host}: "
 
-  "${DANETOOL}" --check "${host}" >/dev/null 2>&1
-  if [ $? != 0 ];then
-    echo "Error checking ${host}"
-    exit 1
-  fi
-  echo "ok"
+	"${DANETOOL}" --check "${host}" >/dev/null 2>&1
+	if [ $? != 0 ]; then
+		echo "Error checking ${host}"
+		exit 1
+	fi
+	echo "ok"
 done
 
 echo ""
 echo "*** Testing good SMTP hosts ***"
 #HOSTS="dougbarton.us nlnetlabs.nl"
 HOSTS="nlnetlabs.nl"
-for host in ${HOSTS};do
-  echo -n "${host}: "
+for host in ${HOSTS}; do
+	echo -n "${host}: "
 
-  "${DANETOOL}" --check "${host}" --port 25 >/dev/null 2>&1
-  if [ $? != 0 ];then
-    echo "Error checking ${host}"
-    exit 1
-  fi
-  echo "ok"
+	"${DANETOOL}" --check "${host}" --port 25 >/dev/null 2>&1
+	if [ $? != 0 ]; then
+		echo "Error checking ${host}"
+		exit 1
+	fi
+	echo "ok"
 done
 
 echo ""
@@ -69,14 +69,14 @@ echo "*** Testing bad HTTPS hosts ***"
 # used to work: dane-broken.rd.nic.fr
 HOSTS="bad-hash.dane.verisignlabs.com bad-params.dane.verisignlabs.com"
 HOSTS="${HOSTS} bad-sig.dane.verisignlabs.com"
-for host in ${HOSTS};do
-  echo -n "${host}: "
-  "${DANETOOL}" --check "${host}" >/dev/null 2>&1
-  if [ $? = 0 ];then
-    echo "Checking ${host} should have failed"
-    exit 1
-  fi
-  echo "ok"
+for host in ${HOSTS}; do
+	echo -n "${host}: "
+	"${DANETOOL}" --check "${host}" >/dev/null 2>&1
+	if [ $? = 0 ]; then
+		echo "Checking ${host} should have failed"
+		exit 1
+	fi
+	echo "ok"
 done
 
 
diff --git a/tests/suite/testrng b/tests/suite/testrng
--- a/tests/suite/testrng
+++ b/tests/suite/testrng
@@ -20,22 +20,22 @@
 
 srcdir="${srcdir:-.}"
 
-if ! test -x "/usr/bin/dieharder";then
-  exit 77
+if ! test -x "/usr/bin/dieharder"; then
+	exit 77
 fi
 
 VERSION=`dieharder -l|grep version|cut -d ' ' -f 6`
 
-if test "$1" = "full";then
-  OPTIONS="-a"
+if test "$1" = "full"; then
+	OPTIONS="-a"
 else
-  if test "${VERSION}" = "2.28.1";then
-    OPTIONS="-d 5"
-    OPTIONS2="-d 10"
-  else
-    OPTIONS="-d 202"
-    OPTIONS2="-d 10"
-  fi
+	if test "${VERSION}" = "2.28.1"; then
+		OPTIONS="-d 5"
+		OPTIONS2="-d 10"
+	else
+		OPTIONS="-d 202"
+		OPTIONS2="-d 10"
+	fi
 fi
 
 OUTFILE=rng.log
@@ -51,9 +51,9 @@ rm -f "${RNGFILE2}"
 
 RINPUTNO=`dieharder -g -1|grep file_input_raw|cut -d '|' -f 2|cut -d ' ' -f 1`
 
-if test -z "${RINPUTNO}";then
-  echo "Cannot determine dieharder option for raw file input, assuming 201"
-  RINPUTNO=201
+if test -z "${RINPUTNO}"; then
+	echo "Cannot determine dieharder option for raw file input, assuming 201"
+	RINPUTNO=201
 fi
 
 echo ""
@@ -64,31 +64,31 @@ echo "Testing nonce PRNG"
 cmp "${RNGFILE}" "${RNGFILE2}"  >/dev/null 2>&1
 ret=$?
 
-if test ${ret} = 0;then
-  echo "numbers are repeated in nonce!"
-  exit 1
+if test ${ret} = 0; then
+	echo "numbers are repeated in nonce!"
+	exit 1
 fi
 
 ./rng nonce 100000000 "${RNGFILE}"
 
 dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
-if ! test -z "${OPTIONS2}";then
-  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}"; then
+	dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
 grep FAILED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "${ret}" = "0";then
-  echo "test failed for nonce"
-  exit 1
+if test "${ret}" = "0"; then
+	echo "test failed for nonce"
+	exit 1
 fi
 
 grep PASSED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "${ret}" != "0";then
-  echo "could not run dieharder test?"
-  exit 1
+if test "${ret}" != "0"; then
+	echo "could not run dieharder test?"
+	exit 1
 fi
 
 cat "${OUTFILE}"
@@ -101,32 +101,32 @@ echo "Testing key PRNG"
 cmp "${RNGFILE}" "${RNGFILE2}" >/dev/null 2>&1
 ret=$?
 
-if test ${ret} = 0;then
-  echo "numbers are repeated in nonce!"
-  exit 1
+if test ${ret} = 0; then
+	echo "numbers are repeated in nonce!"
+	exit 1
 fi
 
 ./rng key 100000000 "${RNGFILE}"
 
 dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
-if ! test -z "${OPTIONS2}";then
-  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}"; then
+	dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
 grep FAILED "${OUTFILE}" >/dev/null 2>&1 
 ret=$?
 
 
-if test "${ret}" = "0";then
-  echo "test failed for key"
-  exit 1
+if test "${ret}" = "0"; then
+	echo "test failed for key"
+	exit 1
 fi
 
 grep PASSED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "${ret}" != "0";then
-  echo "could not run dieharder test?"
-  exit 1
+if test "${ret}" != "0"; then
+	echo "could not run dieharder test?"
+	exit 1
 fi
 
 cat "${OUTFILE}"
@@ -136,23 +136,23 @@ echo "Testing /dev/zero PRNG"
 dd if=/dev/zero of="${RNGFILE}" bs=4 count=10000000 >/dev/null 2>&1
 
 dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS} >"${OUTFILE}" 2>&1
-if ! test -z "${OPTIONS2}";then
-  dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
+if ! test -z "${OPTIONS2}"; then
+	dieharder -f "${RNGFILE}" -g ${RINPUTNO} ${OPTIONS2} >>"${OUTFILE}" 2>&1
 fi
 grep PASSED "${OUTFILE}" >/dev/null 2>&1 
 ret=$?
 
-if test "${ret}" = "0";then
-  echo "test succeeded for /dev/zero!!!"
-  exit 1
+if test "${ret}" = "0"; then
+	echo "test succeeded for /dev/zero!!!"
+	exit 1
 fi
 
 grep FAILED "${OUTFILE}" >/dev/null 2>&1
 ret=$?
 
-if test "${ret}" != "0";then
-  echo "could not run dieharder test?"
-  exit 1
+if test "${ret}" != "0"; then
+	echo "could not run dieharder test?"
+	exit 1
 fi
 
 cat "${OUTFILE}"
diff --git a/tests/suite/testsrn b/tests/suite/testsrn
--- a/tests/suite/testsrn
+++ b/tests/suite/testsrn
@@ -25,8 +25,8 @@ SERV="${SERV:-../../src/gnutls-serv${EXEEXT}} -q"
 CLI="${CLI:-../../src/gnutls-cli${EXEEXT}}"
 unset RETCODE
 
-if test "${WINDIR}" != "";then
-  exit 77
+if test "${WINDIR}" != ""; then
+	exit 77
 fi 
 
 . "${srcdir}/../scripts/common.sh"
@@ -40,19 +40,19 @@ PID=$!
 wait_server ${PID}
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NONE:+AES-128-CBC:+MD5:+SHA1:+VERS-TLS1.0:+ANON-DH:+COMP-NULL:%SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "0. Renegotiation should have succeeded!"
+	fail ${PID} "0. Renegotiation should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "1. Safe rehandshake should have succeeded!"
+	fail ${PID} "1. Safe rehandshake should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%UNSAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "2. Unsafe rehandshake should have succeeded!"
+	fail ${PID} "2. Unsafe rehandshake should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "3. Unsafe negotiation should have succeeded!"
+	fail ${PID} "3. Unsafe negotiation should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "4. Unsafe renegotiation should have failed!"
+	fail ${PID} "4. Unsafe renegotiation should have failed!"
 
 
 kill ${PID}
@@ -63,16 +63,16 @@ PID=$!
 wait_server ${PID}
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "5. Safe rehandshake should have succeeded!"
+	fail ${PID} "5. Safe rehandshake should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%UNSAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "6. Unsafe rehandshake should have succeeded!"
+	fail ${PID} "6. Unsafe rehandshake should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "7. Unsafe negotiation should have failed!"
+	fail ${PID} "7. Unsafe negotiation should have failed!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "8. Unsafe renegotiation should have failed!"
+	fail ${PID} "8. Unsafe renegotiation should have failed!"
 
 kill ${PID}
 wait
@@ -82,16 +82,16 @@ PID=$!
 wait_server ${PID}
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --priority NORMAL:+ANON-DH:%SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 && \
-  fail ${PID} "9. Initial connection should have failed!"
+	fail ${PID} "9. Initial connection should have failed!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --priority NORMAL:+ANON-DH:%UNSAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "10. Unsafe connection should have succeeded!"
+	fail ${PID} "10. Unsafe connection should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "11. Unsafe negotiation should have succeeded!"
+	fail ${PID} "11. Unsafe negotiation should have succeeded!"
 
 "${CLI}" -p "${PORT}" 127.0.0.1 --rehandshake --priority NORMAL:+ANON-DH:%DISABLE_SAFE_RENEGOTIATION </dev/null >/dev/null 2>&1 || \
-  fail ${PID} "12. Unsafe renegotiation should have succeeded!"
+	fail ${PID} "12. Unsafe renegotiation should have succeeded!"
 
 kill ${PID}
 wait
diff --git a/tests/userid/userid b/tests/userid/userid
--- a/tests/userid/userid
+++ b/tests/userid/userid
@@ -23,12 +23,12 @@
 srcdir="${srcdir:-.}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 
-$CERTTOOL --certificate-info --infile "${srcdir}/userid.pem" >out 2>&1
+"${CERTTOOL}" --certificate-info --infile "${srcdir}/userid.pem" >out 2>&1
 RET=$?
-if [ ${RET} !=  0 ];then
-  echo "Error in userid:"
-  cat out
-  exit 1
+if [ ${RET} !=  0 ]; then
+	echo "Error in userid:"
+	cat out
+	exit 1
 fi
 
 rm -f out
