cert-tests: verify --no-text switch for cert/crq/pub/privkeys
Signed-off-by: Dmitry Eremin-Solenikov <dbaryshkov@gmail.com>

diff --git a/tests/cert-tests/crl b/tests/cert-tests/crl
--- a/tests/cert-tests/crl
+++ b/tests/cert-tests/crl
@@ -39,6 +39,7 @@ OUTFILE=out-crl.$$.tmp
 INFOFILE=out-crl-info.$$.tmp
 OUTFILE2=out2-crl.$$.tmp
 TMPFILE=crl.$$.tmpl
+TMP2FILE=crl.$$.tmp2
 
 echo "crl_next_update = 43" >$TMPFILE
 echo "crl_number = 7" >>$TMPFILE
@@ -52,6 +53,19 @@ rc=$?
 if test "${rc}" != "0"; then
 	echo "CRL generation failed"
 	exit ${rc}
+fi
+
+${VALGRIND} "${CERTTOOL}" --crl-info --infile ${OUTFILE} --no-text >${TMP2FILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text crl info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$\|^[A-Za-z0-9/+=]\+$\|^-----END [A-Z0-9 ]\+-----$' ${TMP2FILE} ; then
+	echo "--no-text crl info failed 2"
+	exit 1
 fi
 
 grep "Revoked certificates (152)" "${INFOFILE}" >/dev/null 2>&1
@@ -289,5 +303,6 @@ rm -f "${OUTFILE}"
 rm -f "${INFOFILE}"
 rm -f "${OUTFILE2}"
 rm -f "${TMPFILE}"
+rm -f "${TMP2FILE}"
 
 exit 0
diff --git a/tests/cert-tests/crq b/tests/cert-tests/crq
--- a/tests/cert-tests/crq
+++ b/tests/cert-tests/crq
@@ -66,6 +66,19 @@ datefudge -s "2007-04-22" \
 		--template "${srcdir}/templates/template-tlsfeature.tmpl" \
 		--outfile $OUTFILE 2>/dev/null
 
+${CERTTOOL} --crq-info --no-text --infile ${OUTFILE} > ${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text crq info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$\|^[A-Za-z0-9/+=]\+$\|^-----END [A-Z0-9 ]\+-----$' ${TMPFILE} ; then
+	echo "--no-text crq info failed 2"
+	exit 1
+fi
+
 datefudge -s "2007-04-22" \
 	"${CERTTOOL}" --generate-certificate \
 		--load-ca-privkey "${srcdir}/data/template-test.key" \
diff --git a/tests/cert-tests/pem-decoding b/tests/cert-tests/pem-decoding
--- a/tests/cert-tests/pem-decoding
+++ b/tests/cert-tests/pem-decoding
@@ -179,6 +179,48 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/cert-ecc256.pem" --no-text >${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text -k --certificate-info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$\|^[A-Za-z0-9/+=]\+$\|^-----END [A-Z0-9 ]\+-----$' ${TMPFILE} ; then
+	echo "--no-text -k --certificate-info failed 2"
+	exit 1
+fi
+
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --certificate-pubkey --infile "${srcdir}/data/cert-ecc256.pem" --no-text >${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text cert pubkey failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$\|^[A-Za-z0-9/+=]\+$\|^-----END [A-Z0-9 ]\+-----$' ${TMPFILE} ; then
+	echo "--no-text cert pubkey failed 2"
+	exit 1
+fi
+
+#check if --no-text works as expected
+${VALGRIND} "${CERTTOOL}" --pubkey-info --infile "${srcdir}/data/cert-ecc256.pem" --no-text >${TMPFILE}
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "--no-text pubkey info failed 1"
+	exit ${rc}
+fi
+
+if grep -v '^-----BEGIN [A-Z0-9 ]\+-----$\|^[A-Za-z0-9/+=]\+$\|^-----END [A-Z0-9 ]\+-----$' ${TMPFILE} ; then
+	echo "--no-text pubkey info failed 2"
+	exit 1
+fi
+
 rm -f ${TMPFILE} ${TMPFILE1} ${TMPFILE2}
 
 exit 0
