corrected crq test case; reported by Andreas Metzler

diff --git a/tests/cert-tests/crq b/tests/cert-tests/crq
--- a/tests/cert-tests/crq
+++ b/tests/cert-tests/crq
@@ -28,14 +28,23 @@ DIFF=${DIFF:-diff}
 if ! test -z "${VALGRIND}";then
 VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
+OUTFILE=out.tmp
 
-$VALGRIND $CERTTOOL --inder --crq-info --infile $srcdir/crq-invalid.der >/dev/null 2>&1
+$VALGRIND $CERTTOOL --inder --crq-info --infile $srcdir/csr-invalid.der >$OUTFILE 2>&1
 rc=$?
 
 # We're done.
-if test "$rc" != "1"; then
+if test "$rc" != "0"; then
   echo "Invalid crq decoding failed"
   exit $rc
 fi
+
+grep "error: get_key_id" $OUTFILE >/dev/null 2>&1
+if test "$?" != "0"; then
+  echo "crq decoding didn't fail as expected"
+  exit 1
+fi
+
+rm -f $OUTFILE
 
 exit 0
