Added check for GNUTLS-SA-2015-1

diff --git a/tests/cert-tests/invalid-sig b/tests/cert-tests/invalid-sig
--- a/tests/cert-tests/invalid-sig
+++ b/tests/cert-tests/invalid-sig
@@ -29,6 +29,16 @@ if ! test -z "${VALGRIND}";then
 VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
+#check whether a different PKCS #1 signature than the advertized in certificate is tolerated
+$VALGRIND $CERTTOOL -e --infile $srcdir/invalid-sig.pem
+rc=$?
+
+# We're done.
+if test "$rc" = "0"; then
+  echo "Verification of invalid signature (1) failed"
+  exit $rc
+fi
+
 #check whether a different tbsCertificate than the outer signature algorithm is tolerated
 $VALGRIND $CERTTOOL -e --infile $srcdir/invalid-sig2.pem
 rc=$?
