fuzz: added fuzzer for certificate verification
This also adds a reproducer for CVE-2019-3829.

Resolves: #694

Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>

diff --git a/tests/cert-tests/invalid-sig b/tests/cert-tests/invalid-sig
--- a/tests/cert-tests/invalid-sig
+++ b/tests/cert-tests/invalid-sig
@@ -29,6 +29,10 @@ if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
 fi
 
+if ! test -x "${CERTTOOL}"; then
+	exit 77
+fi
+
 #check whether a different PKCS #1 signature than the advertized in certificate is tolerated
 ${VALGRIND} "${CERTTOOL}" -e --infile "${srcdir}/data/invalid-sig.pem"
 rc=$?
@@ -75,7 +79,17 @@ rc=$?
 
 # We're done.
 if test "${rc}" = "0"; then
-	echo "Verification of invalid signature (4) failed"
+	echo "Verification of invalid signature (5) failed"
+	exit ${rc}
+fi
+
+#this was causing a double free; verify that we receive the expected error code
+${VALGRIND} "${CERTTOOL}" --verify-chain --infile "${srcdir}/data/cve-2019-3829.pem"
+rc=$?
+
+# We're done.
+if test "${rc}" != "1"; then
+	echo "Verification of invalid signature (6) failed"
 	exit ${rc}
 fi
 
