tests: added test case with invalid openpgp cert
This triggers a memory error. Issue found using oss-fuzz:
  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=346

Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>

diff --git a/tests/cert-tests/openpgp-cert-parser b/tests/cert-tests/openpgp-cert-parser
--- a/tests/cert-tests/openpgp-cert-parser
+++ b/tests/cert-tests/openpgp-cert-parser
@@ -64,4 +64,10 @@ if test $rc != 1;then
 	fail "Parsing should have errored"
 fi
 
+${VALGRIND} "${CERTTOOL}" --inraw --pgp-certificate-info --infile "${srcdir}/data/openpgp-invalid2.pub" 2>&1
+rc=$?
+if test $rc != 1;then
+	fail "Parsing should have errored"
+fi
+
 exit ${RETCODE:-0}
