tests: added check for XMPP othername generation

diff --git a/tests/cert-tests/othername-test b/tests/cert-tests/othername-test
--- a/tests/cert-tests/othername-test
+++ b/tests/cert-tests/othername-test
@@ -57,9 +57,33 @@ done
 
 # We're done.
 if test "${rc}" != "0"; then
-	echo "Test 1 failed"
+	echo "Test 1 (othername) failed"
 	exit ${rc}
 fi
+
+rc=1
+counter=1
+
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-othername-xmpp.tmpl" \
+		--outfile ${OUTFILE} 2>/dev/null
+
+	${DIFF} "${srcdir}/template-othername-xmpp.pem" ${OUTFILE} >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
+done
+
+# We're done.
+if test "${rc}" != "0"; then
+	echo "Test 1 (xmpp) failed"
+	exit ${rc}
+fi
+
+
 
 rm -f ${OUTFILE}
 
