Added test certificate with multiple XMPP othername SAN fields.

diff --git a/tests/cert-tests/pem-decoding b/tests/cert-tests/pem-decoding
--- a/tests/cert-tests/pem-decoding
+++ b/tests/cert-tests/pem-decoding
@@ -74,6 +74,25 @@ if test "$rc" != "0"; then
   exit $rc
 fi
 
+#check whether the cert with many othernames is decoded as expected
+$CERTTOOL --certificate-info --infile $srcdir/xmpp-othername.pem >tmp-pem.pem
+rc=$?
+
+if test "$rc" != "0"; then
+  echo "XMPP cert decoding failed 1"
+  exit $rc
+fi
+
+cat $srcdir/xmpp-othername.pem |grep -v "Not After:" >tmp1
+cat tmp-pem.pem |grep -v "Not After:" >tmp2
+$DIFF tmp1 tmp2 || $DIFF --strip-trailing-cr tmp1 tmp2
+rc=$?
+
+if test "$rc" != "0"; then
+  echo "XMPP cert decoding failed 2"
+  exit $rc
+fi
+
 rm -f tmp-pem.pem tmp1 tmp2
 
 exit 0
