tests: added check of GOST cert decoding/printing
This verifies whether our printing functions print the
OID on unknown/unsupported algorithms.

diff --git a/tests/cert-tests/pem-decoding b/tests/cert-tests/pem-decoding
--- a/tests/cert-tests/pem-decoding
+++ b/tests/cert-tests/pem-decoding
@@ -113,6 +113,24 @@ if test "${rc}" != "0"; then
 	exit ${rc}
 fi
 
+
+#check whether the cert with GOST parameters is decoded as expected
+${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/gost-cert.pem" >tmp-pem.pem
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "GOST cert decoding failed 1"
+	exit ${rc}
+fi
+
+${DIFF} tmp-pem.pem gost-cert.pem || ${DIFF} --strip-trailing-cr tmp-pem.pem gost-cert.pem
+rc=$?
+
+if test "${rc}" != "0"; then
+	echo "GOST cert decoding failed 2"
+	exit ${rc}
+fi
+
 rm -f tmp-pem.pem tmp1 tmp2
 
 exit 0
