tests: introduced verification constraints checks for PKCS#7 structures
That is, key purpose checks and more elaborate time checks.

diff --git a/tests/cert-tests/pkcs7 b/tests/cert-tests/pkcs7
--- a/tests/cert-tests/pkcs7
+++ b/tests/cert-tests/pkcs7
@@ -26,8 +26,12 @@ DIFF="${DIFF:-diff -b -B}"
 if ! test -z "${VALGRIND}"; then
 	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
-OUTFILE=out-pkcs7.tmp
-OUTFILE2=out2-pkcs7.tmp
+OUTFILE=out-pkcs7.$$.tmp
+OUTFILE2=out2-pkcs7.$$.tmp
+
+. ${srcdir}/../scripts/common.sh
+
+check_for_datefudge
 
 for FILE in single-ca.p7b full.p7b; do
 ${VALGRIND} "${CERTTOOL}" --inder --p7-info --infile "${srcdir}/data/${FILE}"|grep -v "Signing time" >"${OUTFILE}"
@@ -49,6 +53,36 @@ done
 # check signatures
 
 for FILE in full.p7b; do
+# check validation with date prior to CA issuance
+datefudge -s "2011-1-10" \
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/data/${FILE}" >"${OUTFILE}"
+rc=$?
+
+if test "${rc}" = "0"; then
+	echo "${FILE}: PKCS7 verification succeeded with invalid date (1)"
+	exit 1
+fi
+
+# check validation with date prior to intermediate cert issuance
+datefudge -s "2011-5-28 08:38:00 UTC" \
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/data/${FILE}" >"${OUTFILE}"
+rc=$?
+
+if test "${rc}" = "0"; then
+	echo "${FILE}: PKCS7 verification succeeded with invalid date (2)"
+	exit 1
+fi
+
+# check validation with date after intermediate cert issuance
+datefudge -s "2038-10-12" \
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/data/${FILE}" >"${OUTFILE}"
+rc=$?
+
+if test "${rc}" = "0"; then
+	echo "${FILE}: PKCS7 verification succeeded with invalid date (3)"
+	exit 1
+fi
+
 ${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/data/${FILE}" >"${OUTFILE}"
 rc=$?
 
diff --git a/tests/suite/pkcs7-cat b/tests/suite/pkcs7-cat
--- a/tests/suite/pkcs7-cat
+++ b/tests/suite/pkcs7-cat
@@ -28,12 +28,26 @@ if ! test -z "${VALGRIND}"; then
 fi
 OUTFILE=out-pkcs7.$$.tmp
 
+. ${srcdir}/../scripts/common.sh
+
+check_for_datefudge
+
 #try verification
+datefudge -s "2010-10-10" \
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --infile "${srcdir}/data/test1.cat" --load-certificate "${srcdir}/data/ca.pem"
+rc=$?
+
+if test "${rc}" = "0"; then
+	echo "PKCS7 verification succeeded with invalid date"
+	exit 1
+fi
+
+datefudge -s "2016-10-10" \
 ${VALGRIND} "${CERTTOOL}" --inder --p7-verify --infile "${srcdir}/data/test1.cat" --load-certificate "${srcdir}/data/ca.pem"
 rc=$?
 
 if test "${rc}" != "0"; then
-	echo "${FILE}: PKCS7 verification failed"
+	echo "PKCS7 verification failed"
 	exit ${rc}
 fi
 
