tests: cert-tests: cleanup shell usage
Add quotes for most usages of variables.

Added ${} for variables.

Cleanup trailing spaces.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

diff --git a/tests/cert-tests/pkcs7 b/tests/cert-tests/pkcs7
--- a/tests/cert-tests/pkcs7
+++ b/tests/cert-tests/pkcs7
@@ -20,9 +20,9 @@
 
 #set -e
 
-srcdir=${srcdir:-.}
-CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
-DIFF=${DIFF:-diff}
+srcdir="${srcdir:-.}"
+CERTTOOL="${CERTTOOL:-../../src/certtool$EXEEXT}"
+DIFF="${DIFF:-diff}"
 if ! test -z "${VALGRIND}";then
 VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
 fi
@@ -30,18 +30,18 @@ OUTFILE=out-pkcs7.tmp
 OUTFILE2=out2-pkcs7.tmp
 
 for FILE in single-ca.p7b full.p7b;do
-$VALGRIND $CERTTOOL --inder --p7-info --infile $srcdir/$FILE|grep -v "Signing time" >$OUTFILE
+${VALGRIND} "${CERTTOOL}" --inder --p7-info --infile "${srcdir}/${FILE}"|grep -v "Signing time" >"${OUTFILE}"
 rc=$?
 
 # We're done.
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 decoding failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 decoding failed"
+  exit ${rc}
 fi
 
-$DIFF $OUTFILE $srcdir/$FILE.out >/dev/null
+${DIFF} "${OUTFILE}" "${srcdir}/${FILE}.out" >/dev/null
 if test "$?" != "0"; then
-  echo "$FILE: PKCS7 decoding didn't produce the correct file"
+  echo "${FILE}: PKCS7 decoding didn't produce the correct file"
   exit 1
 fi
 done
@@ -49,27 +49,27 @@ done
 # check signatures
 
 for FILE in full.p7b;do
-$VALGRIND $CERTTOOL --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 verification failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 verification failed"
+  exit ${rc}
 fi
 
-$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.1 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
+${VALGRIND} "${CERTTOOL}" --verify-purpose=1.3.6.1.5.5.7.3.1 --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 verification failed with key purpose"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 verification failed with key purpose"
+  exit ${rc}
 fi
 
-$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.3 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
+${VALGRIND} "${CERTTOOL}" --verify-purpose=1.3.6.1.5.5.7.3.3 --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" = "0"; then
-  echo "$FILE: PKCS7 verification succeeded with wrong key purpose"
+if test "${rc}" = "0"; then
+  echo "${FILE}: PKCS7 verification succeeded with wrong key purpose"
   exit 2
 fi
 
@@ -77,123 +77,123 @@ done
 
 # check signature with detached data
 
-FILE=detached.p7b
-$VALGRIND $CERTTOOL --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE
+FILE="detached.p7b"
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}"
 rc=$?
 
-if test "$rc" = "0"; then
-  echo "$FILE: PKCS7 verification succeeded without providing detached data"
+if test "${rc}" = "0"; then
+  echo "${FILE}: PKCS7 verification succeeded without providing detached data"
   exit 2
 fi
 
-$VALGRIND $CERTTOOL --inder --p7-verify --load-data $srcdir/pkcs7-detached.txt --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE
+${VALGRIND} "${CERTTOOL}" --inder --p7-verify --load-data "${srcdir}/pkcs7-detached.txt" --load-ca-certificate "${srcdir}/../../doc/credentials/x509/ca.pem" --infile "${srcdir}/${FILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 verification failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 verification failed"
+  exit ${rc}
 fi
 
 # Test cert combination
 
 FILE="p7-combined"
-cat $srcdir/../certs/cert*.pem >$OUTFILE2
-$VALGRIND $CERTTOOL --p7-generate --load-certificate $OUTFILE2 >$OUTFILE
+cat "${srcdir}/../certs"/cert*.pem >"${OUTFILE2}"
+${VALGRIND} "${CERTTOOL}" --p7-generate --load-certificate "${OUTFILE2}" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct generation failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct generation failed"
+  exit ${rc}
 fi
 
-$DIFF $OUTFILE $srcdir/p7-combined.out >/dev/null
+${DIFF} "${OUTFILE}" "${srcdir}/p7-combined.out" >/dev/null
 if test "$?" != "0"; then
-  echo "$FILE: PKCS7 generation didn't produce the correct file"
+  echo "${FILE}: PKCS7 generation didn't produce the correct file"
   exit 1
 fi
 
 # Test signing
-FILE=signing
-$VALGRIND $CERTTOOL --p7-sign --load-privkey  $srcdir/../../doc/credentials/x509/key-rsa.pem --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --infile $srcdir/pkcs7-detached.txt >$OUTFILE
+FILE="signing"
+${VALGRIND} "${CERTTOOL}" --p7-sign --load-privkey  "${srcdir}/../../doc/credentials/x509/key-rsa.pem" --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --infile "${srcdir}/pkcs7-detached.txt" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing failed"
+  exit ${rc}
 fi
 
-FILE=signing-verify
-$VALGRIND $CERTTOOL --p7-verify --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem <$OUTFILE
+FILE="signing-verify"
+${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" <"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing failed verification"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing failed verification"
+  exit ${rc}
 fi
 
 
-FILE=signing-detached
-$VALGRIND $CERTTOOL --p7-detached-sign --load-privkey  $srcdir/../../doc/credentials/x509/key-rsa.pem --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --infile $srcdir/pkcs7-detached.txt >$OUTFILE
+FILE="signing-detached"
+${VALGRIND} "${CERTTOOL}" --p7-detached-sign --load-privkey  "${srcdir}/../../doc/credentials/x509/key-rsa.pem" --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --infile "${srcdir}/pkcs7-detached.txt" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing-detached failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing-detached failed"
+  exit ${rc}
 fi
 
-FILE=signing-detached-verify
-$VALGRIND $CERTTOOL --p7-verify --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --load-data $srcdir/pkcs7-detached.txt <$OUTFILE
+FILE="signing-detached-verify"
+${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --load-data "${srcdir}/pkcs7-detached.txt" <"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing-detached failed verification"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing-detached failed verification"
+  exit ${rc}
 fi
 
 # Test signing with broken algorithms
-FILE=signing-broken
-$VALGRIND $CERTTOOL --hash md5 --p7-sign --load-privkey  $srcdir/../../doc/credentials/x509/key-rsa.pem --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --infile $srcdir/pkcs7-detached.txt >$OUTFILE
+FILE="signing-broken"
+${VALGRIND} "${CERTTOOL}" --hash md5 --p7-sign --load-privkey  "${srcdir}/../../doc/credentials/x509/key-rsa.pem" --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --infile "${srcdir}/pkcs7-detached.txt" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing-broken failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing-broken failed"
+  exit ${rc}
 fi
 
-FILE=signing-verify-broken
-$VALGRIND $CERTTOOL --p7-verify --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem <$OUTFILE
+FILE="signing-verify-broken"
+${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" <"${OUTFILE}"
 rc=$?
 
-if test "$rc" = "0"; then
-  echo "$FILE: PKCS7 struct verification succeeded with broken algo"
+if test "${rc}" = "0"; then
+  echo "${FILE}: PKCS7 struct verification succeeded with broken algo"
   exit 1
 fi
 
-FILE=signing-time
-$VALGRIND $CERTTOOL --p7-detached-sign --p7-time --load-privkey  $srcdir/../../doc/credentials/x509/key-rsa.pem --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --infile $srcdir/pkcs7-detached.txt >$OUTFILE
+FILE="signing-time"
+${VALGRIND} "${CERTTOOL}" --p7-detached-sign --p7-time --load-privkey  "${srcdir}/../../doc/credentials/x509/key-rsa.pem" --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --infile "${srcdir}/pkcs7-detached.txt" >"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing with time failed"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing with time failed"
+  exit ${rc}
 fi
 
-$VALGRIND $CERTTOOL --p7-info <$OUTFILE|grep "Signing time:" $OUTFILE >/dev/null 2>&1
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing with time failed. No time was found."
-  exit $rc
+${VALGRIND} "${CERTTOOL}" --p7-info <"${OUTFILE}"|grep "Signing time:" "${OUTFILE}" >/dev/null 2>&1
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing with time failed. No time was found."
+  exit ${rc}
 fi
 
-FILE=signing-time-verify
-$VALGRIND $CERTTOOL --p7-verify --load-certificate $srcdir/../../doc/credentials/x509/cert-rsa.pem --load-data $srcdir/pkcs7-detached.txt <$OUTFILE
+FILE="signing-time-verify"
+${VALGRIND} "${CERTTOOL}" --p7-verify --load-certificate "${srcdir}/../../doc/credentials/x509/cert-rsa.pem" --load-data "${srcdir}/pkcs7-detached.txt" <"${OUTFILE}"
 rc=$?
 
-if test "$rc" != "0"; then
-  echo "$FILE: PKCS7 struct signing with time failed verification"
-  exit $rc
+if test "${rc}" != "0"; then
+  echo "${FILE}: PKCS7 struct signing with time failed verification"
+  exit ${rc}
 fi
 
-rm -f $OUTFILE
-rm -f $OUTFILE2
+rm -f "${OUTFILE}"
+rm -f "${OUTFILE2}"
 
 exit 0
