tests: check the key purpose in PKCS #7 verification

diff --git a/tests/cert-tests/pkcs7 b/tests/cert-tests/pkcs7
--- a/tests/cert-tests/pkcs7
+++ b/tests/cert-tests/pkcs7
@@ -51,11 +51,27 @@ for FILE in full.p7b;do
 $VALGRIND $CERTTOOL --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
 rc=$?
 
-# We're done.
 if test "$rc" != "0"; then
   echo "$FILE: PKCS7 verification failed"
   exit $rc
 fi
+
+$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.1 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
+rc=$?
+
+if test "$rc" != "0"; then
+  echo "$FILE: PKCS7 verification failed with key purpose"
+  exit $rc
+fi
+
+$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.3 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
+rc=$?
+
+if test "$rc" = "0"; then
+  echo "$FILE: PKCS7 verification succeeded with wrong key purpose"
+  exit 2
+fi
+
 done
 
 rm -f $OUTFILE
