tests: verify that unique IDs are generated as expected

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -226,6 +226,7 @@ fi
 
 rm -f tmp-tt.pem
 
+
 # Test the GeneralizedTime support
 if test "$(getconf LONG_BIT)" = "64"; then
 	# we should test that on systems which have 64-bit time_t.
@@ -250,6 +251,32 @@ if test "$(getconf LONG_BIT)" = "64"; then
 		echo "Test 8 (generalizedTime) failed"
 		exit ${rc}
 	fi
+fi
+
+rm -f tmp-tt.pem
+
+# Test unique ID field generation
+
+rc=1
+counter=1
+
+while [ "${rc}" != "0" -a $counter -le 3 ]; do
+	datefudge "2007-04-22" \
+	"${CERTTOOL}" --generate-self-signed \
+		--load-privkey "${srcdir}/template-test.key" \
+		--template "${srcdir}/template-unique.tmpl" \
+		--outfile tmp-tt.pem 2>/dev/null
+
+	${DIFF} "${srcdir}/template-unique.pem" tmp-tt.pem >/dev/null 2>&1
+	rc=$?
+	test ${rc} != 0 && sleep 3
+	counter=`expr $counter + 1`
+done
+
+# We're done.
+if test "${rc}" != "0"; then
+	echo "Test 9 (unique ID) failed"
+	exit ${rc}
 fi
 
 rm -f tmp-tt.pem
