tests: template-test: added a baseline check to detect slow systems

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -37,9 +37,35 @@ fi
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
-      
+
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-basic.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-basic.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Baseline test failed, is system slow?"
+  exit 77
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 10 ]
+do
+
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
     --load-privkey $srcdir/template-test.key \
@@ -49,6 +75,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-test.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -62,7 +89,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -73,6 +100,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-utf8.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -86,7 +114,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -97,6 +125,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-dn.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -124,7 +153,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -135,6 +164,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-overflow.pem tmp-tt.pem >/dev/null 2>&1 
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -148,7 +178,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -159,6 +189,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-overflow2.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -172,7 +203,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -183,6 +214,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-date.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
@@ -198,7 +230,7 @@ rm -f tmp-tt.pem
 rc=1
 counter=1
 
-while [ "$rc" != "0" -a $counter -le 3 ]
+while [ "$rc" != "0" -a $counter -le 10 ]
 do
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
@@ -209,6 +241,7 @@ datefudge "2007-04-22" \
 diff $srcdir/template-nc.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
 counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
 done
 
 # We're done.
