tests: template-test: added a baseline check to detect slow systems

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -39,7 +39,33 @@ counter=1
 
 while [ "$rc" != "0" -a $counter -le 10 ]
 do
-      
+
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-basic.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-basic.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+test "$rc" != 0 && sleep 1
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Baseline test failed, is system slow?"
+  exit 77
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 10 ]
+do
+
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
     --load-privkey $srcdir/template-test.key \
