tests: verify that we generate dates with UTCTime prior to 2050
Also that we generate dates with GeneralizedTime format after 2050.

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -223,5 +223,32 @@ fi
 
 rm -f tmp-tt.pem
 
+# Test the GeneralizedTime support
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+      
+datefudge "2051-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-generalized.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-generalized.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+test $rc != 0 && sleep 3
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 8 (generalizedTime) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
 
 exit 0
