tests: check explicitly the size of time_t
Previously we were disabling the 2038 tests on 32-bit systems,
but there can be 32-bit systems with a 64-bit time_t. Ensure
that we run the right tests.

Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -21,7 +21,7 @@
 #set -e
 
 srcdir="${srcdir:-.}"
-ac_cv_sizeof_unsigned_long_int="${ac_cv_sizeof_unsigned_long_int:-8}"
+ac_cv_sizeof_time_t="${ac_cv_sizeof_time_t:-8}"
 CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
 DIFF="${DIFF:-diff}"
 
@@ -35,6 +35,8 @@ TMPFILE=tmp-tt.pem.$$.tmp
 . ${srcdir}/../scripts/common.sh
 
 check_for_datefudge
+
+echo "Running test for ${ac_cv_sizeof_time_t}-byte time_t"
 
 # Note that in rare cases this test may fail because the
 # time set using datefudge could have changed since the generation
@@ -123,7 +125,6 @@ fi
 rm -f ${TMPFILE}
 
 # The following test works in 64-bit systems
-if test "${ac_cv_sizeof_unsigned_long_int}" = 8;then
 
 datefudge -s "2007-04-22" \
 	"${CERTTOOL}" --generate-self-signed \
@@ -131,17 +132,25 @@ datefudge -s "2007-04-22" \
 		--template "${srcdir}/templates/template-overflow2.tmpl" \
 		--outfile ${TMPFILE} 2>/dev/null
 
-${DIFF} "${srcdir}/data/template-overflow2.pem" ${TMPFILE} >/dev/null 2>&1
 rc=$?
+if test "${ac_cv_sizeof_time_t}" = 8;then
+	if test "$rc" != "0"; then
+		echo "Test 5-1 (overflow2) failed"
+		exit ${rc}
+	fi
 
-# We're done.
-if test "${rc}" != "0"; then
-	echo "Test 5 (overflow2) failed"
-	exit ${rc}
+	${DIFF} "${srcdir}/data/template-overflow2.pem" ${TMPFILE} #>/dev/null 2>&1
+	rc=$?
+
+	# We're done.
+	if test "${rc}" != "0"; then
+	echo $TMPFILE
+		echo "Test 5-2 (overflow2) failed"
+		exit ${rc}
+	fi
+
 fi
-
 rm -f ${TMPFILE}
-fi
 
 datefudge -s "2007-04-22" \
 	"${CERTTOOL}" --generate-self-signed \
@@ -181,7 +190,7 @@ rm -f ${TMPFILE}
 
 
 # Test the GeneralizedTime support
-if test "${ac_cv_sizeof_unsigned_long_int}" = 8;then
+if test "${ac_cv_sizeof_time_t}" = 8;then
 	# we should test that on systems which have 64-bit time_t.
 	datefudge -s "2051-04-22" \
 			"${CERTTOOL}" --generate-self-signed \
