Added test on UTF-8 certificate generation.

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -43,11 +43,29 @@ datefudge "2007-04-22" \
 diff $srcdir/template-test.pem tmp-tt.pem
 rc=$?
 
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 1 failed"
+  exit $rc
+fi
+
 rm -f tmp-tt.pem
+
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-utf8.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-utf8.pem tmp-tt.pem
+rc=$?
 
 # We're done.
 if test "$rc" != "0"; then
+  echo "Test 2 (UTF8) failed"
   exit $rc
 fi
+
+rm -f tmp-tt.pem
 
 exit 0
