certtool allows setting name constraints.

diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -193,6 +193,31 @@ fi
 
 rm -f tmp-tt.pem
 
+# Test name constraints generation
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-nc.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-nc.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 7 (name constraints) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
 
 
 exit 0
